export default [
  "[A-Z]",
  "[a-z]",
  "aàáâæbcćčçdeéèêëfghiíìîïjklmnoóòôœpqrsśŝštuùúûüvwxyýÿz",
  "[0-9]",
  "[A-Za-z0-9]",
  "[FPTVWYfrvwy]",
  "[,._]",
  "[;:]",
  "[-–—+]",
  "(fi|fj|fl|ff|ffi|ffl|fb|fh|fk|ft)",
  "@¡!¿?",
  "@\"\"“”„”„“",
  "@''‘’",
  "@()[]{}<>",
];
