export default [
  "A-Z",
  "a-z",
  "0-9",
  "A-Za-z0-9",
  "FPTVWYfrvwy",
  "aáàâåäãæbcçdðeéèêëfghiíìîïjklmnñoóòôöõøpqrstuúùûüvwxyýÿzþ",
  "aáàăâåäãąāæbcćĉčċçdďđðeéèĕêěëėęēfgğĝġģhĥħiíìĭîïĩįīĳıjĵkķlĺľļłŀmnńňñņŋoóòŏôöőõøōœpqĸrŕřŗsśŝšştťţŧuúùŭûůüűũųūvwŵxyýŷÿÿzźžżþ",
  ",.",
  ";:",
  "-–—+",
  "(fi|fj|fl|ff|ffi|ffl|fb|fh|fk|ft)",
  "@¡!¿?",
  "@“”‘’",
  "@“”„”„“””",
  "@\"\"''",
  "@()[]{}<>",
];
