module.exports = [
  { name: "Abaza", opentypeTag: "ABA ", htmlTag: "abq" },
  { name: "Abkhazian", opentypeTag: "ABK ", htmlTag: "abk" },
  { name: "Acholi", opentypeTag: "ACH ", htmlTag: "ach" },
  { name: "Achi", opentypeTag: "ACR ", htmlTag: "acr" },
  { name: "Adyghe", opentypeTag: "ADY ", htmlTag: "ady" },
  { name: "Afrikaans", opentypeTag: "AFK ", htmlTag: "afr" },
  { name: "Afar", opentypeTag: "AFR ", htmlTag: "aar" },
  { name: "Agaw", opentypeTag: "AGW ", htmlTag: "ahg" },
  { name: "Aiton", opentypeTag: "AIO ", htmlTag: "aio" },
  { name: "Akan", opentypeTag: "AKA ", htmlTag: "aka" },
  { name: "Alsatian", opentypeTag: "ALS ", htmlTag: "gsw" },
  { name: "Altai", opentypeTag: "ALT ", htmlTag: "atv" },
  { name: "Amharic", opentypeTag: "AMH ", htmlTag: "amh" },
  { name: "Anglo-Saxon", opentypeTag: "ANG ", htmlTag: "ang" },
  { name: "Arabic", opentypeTag: "ARA ", htmlTag: "ara" },
  { name: "Aragonese", opentypeTag: "ARG ", htmlTag: "arg" },
  { name: "Aari", opentypeTag: "ARI ", htmlTag: "aiw" },
  { name: "Rakhine", opentypeTag: "ARK ", htmlTag: "mhv" },
  { name: "Assamese", opentypeTag: "ASM ", htmlTag: "asm" },
  { name: "Asturian", opentypeTag: "AST ", htmlTag: "ast" },
  { name: "Athapaskan", opentypeTag: "ATH ", htmlTag: "apk" },
  { name: "Avar", opentypeTag: "AVR ", htmlTag: "ava" },
  { name: "Awadhi", opentypeTag: "AWA ", htmlTag: "awa" },
  { name: "Aymara", opentypeTag: "AYM ", htmlTag: "aym" },
  { name: "Torki", opentypeTag: "AZB ", htmlTag: "azb" },
  { name: "Azerbaijani", opentypeTag: "AZE ", htmlTag: "aze" },
  { name: "Badaga", opentypeTag: "BAD ", htmlTag: "bfq" },
  { name: "Banda", opentypeTag: "BAD0", htmlTag: "bad" },
  { name: "Baghelkhandi", opentypeTag: "BAG ", htmlTag: "bfy" },
  { name: "Balkar", opentypeTag: "BAL ", htmlTag: "krc" },
  { name: "Balinese", opentypeTag: "BAN ", htmlTag: "ban" },
  { name: "Bavarian", opentypeTag: "BAR ", htmlTag: "bar" },
  { name: "Baulé", opentypeTag: "BAU ", htmlTag: "bci" },
  { name: "Batak Toba", opentypeTag: "BBC ", htmlTag: "bbc" },
  { name: "Berber", opentypeTag: "BBR ", htmlTag: "ber" },
  { name: "Bench", opentypeTag: "BCH ", htmlTag: "bcq" },
  { name: "Bandjalang", opentypeTag: "BDY ", htmlTag: "bdy" },
  { name: "Belarussian", opentypeTag: "BEL ", htmlTag: "bel" },
  { name: "Bemba", opentypeTag: "BEM ", htmlTag: "bem" },
  { name: "Bengali", opentypeTag: "BEN ", htmlTag: "ben" },
  { name: "Haryanvi", opentypeTag: "BGC ", htmlTag: "bgc" },
  { name: "Bagri", opentypeTag: "BGQ ", htmlTag: "bgq" },
  { name: "Bulgarian", opentypeTag: "BGR ", htmlTag: "bul" },
  { name: "Bhili", opentypeTag: "BHI ", htmlTag: "bhi" },
  { name: "Bhojpuri", opentypeTag: "BHO ", htmlTag: "bho" },
  { name: "Bikol", opentypeTag: "BIK ", htmlTag: "bik" },
  { name: "Bilen", opentypeTag: "BIL ", htmlTag: "byn" },
  { name: "Bislama", opentypeTag: "BIS ", htmlTag: "bis" },
  { name: "Kanauji", opentypeTag: "BJJ ", htmlTag: "bjj" },
  { name: "Blackfoot", opentypeTag: "BKF ", htmlTag: "bla" },
  { name: "Baluchi", opentypeTag: "BLI ", htmlTag: "bal" },
  { name: "Pa’o Karen", opentypeTag: "BLK ", htmlTag: "blk" },
  { name: "Balante", opentypeTag: "BLN ", htmlTag: "bjt" },
  { name: "Balti", opentypeTag: "BLT ", htmlTag: "bft" },
  { name: "Bambara (Bamanankan)", opentypeTag: "BMB ", htmlTag: "bam" },
  { name: "Bamileke", opentypeTag: "BML ", htmlTag: "bai" },
  { name: "Bosnian", opentypeTag: "BOS ", htmlTag: "bos" },
  { name: "Bishnupriya Manipuri", opentypeTag: "BPY ", htmlTag: "bpy" },
  { name: "Breton", opentypeTag: "BRE ", htmlTag: "bre" },
  { name: "Brahui", opentypeTag: "BRH ", htmlTag: "brh" },
  { name: "Braj Bhasha", opentypeTag: "BRI ", htmlTag: "bra" },
  { name: "Burmese", opentypeTag: "BRM ", htmlTag: "mya" },
  { name: "Bodo", opentypeTag: "BRX ", htmlTag: "brx" },
  { name: "Bashkir", opentypeTag: "BSH ", htmlTag: "bak" },
  { name: "Burushaski", opentypeTag: "BSK ", htmlTag: "bsk" },
  { name: "Beti", opentypeTag: "BTI ", htmlTag: "btb" },
  { name: "Batak Simalungun", opentypeTag: "BTS ", htmlTag: "bts" },
  { name: "Bugis", opentypeTag: "BUG ", htmlTag: "bug" },
  { name: "Medumba", opentypeTag: "BYV ", htmlTag: "byv" },
  { name: "Kaqchikel", opentypeTag: "CAK ", htmlTag: "cak" },
  { name: "Catalan", opentypeTag: "CAT ", htmlTag: "cat" },
  { name: "Zamboanga Chavacano", opentypeTag: "CBK ", htmlTag: "cbk" },
  { name: "Chinantec", opentypeTag: "CCHN", htmlTag: "cco" },
  { name: "Cebuano", opentypeTag: "CEB ", htmlTag: "ceb" },
  { name: "Chechen", opentypeTag: "CHE ", htmlTag: "che" },
  { name: "Chaha Gurage", opentypeTag: "CHG ", htmlTag: "sgw" },
  { name: "Chattisgarhi", opentypeTag: "CHH ", htmlTag: "hne" },
  { name: "Chichewa (Chewa, Nyanja)", opentypeTag: "CHI ", htmlTag: "nya" },
  { name: "Chukchi", opentypeTag: "CHK ", htmlTag: "ckt" },
  { name: "Chuukese", opentypeTag: "CHK0", htmlTag: "chk" },
  { name: "Choctaw", opentypeTag: "CHO ", htmlTag: "cho" },
  { name: "Chipewyan", opentypeTag: "CHP ", htmlTag: "chp" },
  { name: "Cherokee", opentypeTag: "CHR ", htmlTag: "chr" },
  { name: "Chamorro", opentypeTag: "CHA ", htmlTag: "cha" },
  { name: "Chuvash", opentypeTag: "CHU ", htmlTag: "chv" },
  { name: "Cheyenne", opentypeTag: "CHY ", htmlTag: "chy" },
  { name: "Chiga", opentypeTag: "CGG ", htmlTag: "cgg" },
  { name: "Western Cham", opentypeTag: "CJA ", htmlTag: "cja" },
  { name: "Eastern Cham", opentypeTag: "CJM ", htmlTag: "cjm" },
  { name: "Comorian", opentypeTag: "CMR ", htmlTag: "swb" },
  { name: "Coptic", opentypeTag: "COP ", htmlTag: "cop" },
  { name: "Cornish", opentypeTag: "COR ", htmlTag: "cor" },
  { name: "Corsican", opentypeTag: "COS ", htmlTag: "cos" },
  { name: "Creoles", opentypeTag: "CPP ", htmlTag: "crp" },
  { name: "Cree", opentypeTag: "CRE ", htmlTag: "cre" },
  { name: "Carrier", opentypeTag: "CRR ", htmlTag: "crx" },
  { name: "Crimean Tatar", opentypeTag: "CRT ", htmlTag: "crh" },
  { name: "Kashubian", opentypeTag: "CSB ", htmlTag: "csb" },
  { name: "Church Slavonic", opentypeTag: "CSL ", htmlTag: "chu" },
  { name: "Czech", opentypeTag: "CSY ", htmlTag: "ces" },
  { name: "Chittagonian", opentypeTag: "CTG ", htmlTag: "ctg" },
  { name: "San Blas Kuna", opentypeTag: "CUK ", htmlTag: "cuk" },
  { name: "Danish", opentypeTag: "DAN ", htmlTag: "dan" },
  { name: "Dargwa", opentypeTag: "DAR ", htmlTag: "dar" },
  { name: "Dayi", opentypeTag: "DAX ", htmlTag: "dax" },
  { name: "Woods Cree", opentypeTag: "DCR ", htmlTag: "cwd" },
  { name: "German", opentypeTag: "DEU ", htmlTag: "deu" },
  { name: "Dogri", opentypeTag: "DGO ", htmlTag: "dgo" },
  { name: "Dogri", opentypeTag: "DGR ", htmlTag: "doi" },
  { name: "Dhangu", opentypeTag: "DHG ", htmlTag: "dhg" },
  { name: "Divehi (Dhivehi, Maldivian)", opentypeTag: "DHV  (deprecated)", htmlTag: "div" },
  { name: "Dimli", opentypeTag: "DIQ ", htmlTag: "diq" },
  { name: "Divehi (Dhivehi, Maldivian)", opentypeTag: "DIV ", htmlTag: "div" },
  { name: "Zarma", opentypeTag: "DJR ", htmlTag: "dje" },
  { name: "Djambarrpuyngu", opentypeTag: "DJR0", htmlTag: "djr" },
  { name: "Dangme", opentypeTag: "DNG ", htmlTag: "ada" },
  { name: "Dan", opentypeTag: "DNJ ", htmlTag: "dnj" },
  { name: "Dinka", opentypeTag: "DNK ", htmlTag: "din" },
  { name: "Dari", opentypeTag: "DRI ", htmlTag: "prs" },
  { name: "Dhuwal", opentypeTag: "DUJ ", htmlTag: "duj" },
  { name: "Dungan", opentypeTag: "DUN ", htmlTag: "dng" },
  { name: "Dzongkha", opentypeTag: "DZN ", htmlTag: "dzo" },
  { name: "Ebira", opentypeTag: "EBI ", htmlTag: "igb" },
  { name: "Eastern Cree", opentypeTag: "ECR ", htmlTag: "crj" },
  { name: "Edo", opentypeTag: "EDO ", htmlTag: "bin" },
  { name: "Efik", opentypeTag: "EFI ", htmlTag: "efi" },
  { name: "Greek", opentypeTag: "ELL ", htmlTag: "ell" },
  { name: "Eastern Maninkakan", opentypeTag: "EMK ", htmlTag: "emk" },
  { name: "English", opentypeTag: "ENG ", htmlTag: "eng" },
  { name: "Erzya", opentypeTag: "ERZ ", htmlTag: "myv" },
  { name: "Spanish", opentypeTag: "ESP ", htmlTag: "spa" },
  { name: "Central Yupik", opentypeTag: "ESU ", htmlTag: "esu" },
  { name: "Estonian", opentypeTag: "ETI ", htmlTag: "est" },
  { name: "Basque", opentypeTag: "EUQ ", htmlTag: "eus" },
  { name: "Evenki", opentypeTag: "EVK ", htmlTag: "evn" },
  { name: "Even", opentypeTag: "EVN ", htmlTag: "eve" },
  { name: "Ewe", opentypeTag: "EWE ", htmlTag: "ewe" },
  { name: "French Antillean", opentypeTag: "FAN ", htmlTag: "acf" },
  { name: "Fang", opentypeTag: "FAN0", htmlTag: "fan" },
  { name: "Persian", opentypeTag: "FAR ", htmlTag: "fas" },
  { name: "Fanti", opentypeTag: "FAT ", htmlTag: "fat" },
  { name: "Finnish", opentypeTag: "FIN ", htmlTag: "fin" },
  { name: "Fijian", opentypeTag: "FJI ", htmlTag: "fij" },
  { name: "Dutch (Flemish)", opentypeTag: "FLE ", htmlTag: "vls" },
  { name: "Fe’fe’", opentypeTag: "FMP ", htmlTag: "fmp" },
  { name: "Forest Nenets", opentypeTag: "FNE ", htmlTag: "enf" },
  { name: "Fon", opentypeTag: "FON ", htmlTag: "fon" },
  { name: "Faroese", opentypeTag: "FOS ", htmlTag: "fao" },
  { name: "French", opentypeTag: "FRA ", htmlTag: "fra" },
  { name: "Cajun French", opentypeTag: "FRC ", htmlTag: "frc" },
  { name: "Frisian", opentypeTag: "FRI ", htmlTag: "fry" },
  { name: "Friulian", opentypeTag: "FRL ", htmlTag: "fur" },
  { name: "Arpitan", opentypeTag: "FRP ", htmlTag: "frp" },
  { name: "Futa", opentypeTag: "FTA ", htmlTag: "fuf" },
  { name: "Fulah", opentypeTag: "FUL ", htmlTag: "ful" },
  { name: "Nigerian Fulfulde", opentypeTag: "FUV ", htmlTag: "fuv" },
  { name: "Ga", opentypeTag: "GAD ", htmlTag: "gaa" },
  { name: "Scottish Gaelic (Gaelic)", opentypeTag: "GAE ", htmlTag: "gla" },
  { name: "Gagauz", opentypeTag: "GAG ", htmlTag: "gag" },
  { name: "Galician", opentypeTag: "GAL ", htmlTag: "glg" },
  { name: "Garhwali", opentypeTag: "GAW ", htmlTag: "gbm" },
  { name: "Geez", opentypeTag: "GEZ ", htmlTag: "gez" },
  { name: "Githabul", opentypeTag: "GIH ", htmlTag: "gih" },
  { name: "Gilyak", opentypeTag: "GIL ", htmlTag: "niv" },
  { name: "Kiribati (Gilbertese)", opentypeTag: "GIL0", htmlTag: "gil" },
  { name: "Kpelle (Guinea)", opentypeTag: "GKP ", htmlTag: "gkp" },
  { name: "Gilaki", opentypeTag: "GLK ", htmlTag: "glk" },
  { name: "Gumuz", opentypeTag: "GMZ ", htmlTag: "guk" },
  { name: "Gumatj", opentypeTag: "GNN ", htmlTag: "gnn" },
  { name: "Gogo", opentypeTag: "GOG ", htmlTag: "gog" },
  { name: "Gondi", opentypeTag: "GON ", htmlTag: "gon" },
  { name: "Greenlandic", opentypeTag: "GRN ", htmlTag: "kal" },
  { name: "Garo", opentypeTag: "GRO ", htmlTag: "grt" },
  { name: "Guarani", opentypeTag: "GUA ", htmlTag: "grn" },
  { name: "Wayuu", opentypeTag: "GUC ", htmlTag: "guc" },
  { name: "Gupapuyngu", opentypeTag: "GUF ", htmlTag: "guf" },
  { name: "Gujarati", opentypeTag: "GUJ ", htmlTag: "guj" },
  { name: "Gusii", opentypeTag: "GUZ ", htmlTag: "guz" },
  { name: "Haitian (Haitian Creole)", opentypeTag: "HAI ", htmlTag: "hat" },
  { name: "Halam (Falam Chin)", opentypeTag: "HAL ", htmlTag: "flm" },
  { name: "Harauti", opentypeTag: "HAR ", htmlTag: "hoj" },
  { name: "Hausa", opentypeTag: "HAU ", htmlTag: "hau" },
  { name: "Hawaiian", opentypeTag: "HAW ", htmlTag: "haw" },
  { name: "Haya", opentypeTag: "HAY ", htmlTag: "hay" },
  { name: "Hazaragi", opentypeTag: "HAZ ", htmlTag: "haz" },
  { name: "Hammer-Banna", opentypeTag: "HBN ", htmlTag: "amf" },
  { name: "Herero", opentypeTag: "HER ", htmlTag: "her" },
  { name: "Hiligaynon", opentypeTag: "HIL ", htmlTag: "hil" },
  { name: "Hindi", opentypeTag: "HIN ", htmlTag: "hin" },
  { name: "High Mari", opentypeTag: "HMA ", htmlTag: "mrj" },
  { name: "Hmong", opentypeTag: "HMN ", htmlTag: "hmn" },
  { name: "Hiri Motu", opentypeTag: "HMO ", htmlTag: "hmo" },
  { name: "Hindko", opentypeTag: "HND ", htmlTag: "hno" },
  { name: "Ho", opentypeTag: "HO", htmlTag: "hoc" },
  { name: "Harari", opentypeTag: "HRI ", htmlTag: "har" },
  { name: "Croatian", opentypeTag: "HRV ", htmlTag: "hrv" },
  { name: "Hungarian", opentypeTag: "HUN ", htmlTag: "hun" },
  { name: "Armenian", opentypeTag: "HYE ", htmlTag: "hye" },
  { name: "Armenian East", opentypeTag: "HYE0", htmlTag: "hye" },
  { name: "Iban", opentypeTag: "IBA ", htmlTag: "iba" },
  { name: "Ibibio", opentypeTag: "IBB ", htmlTag: "ibb" },
  { name: "Igbo", opentypeTag: "IBO ", htmlTag: "ibo" },
  { name: "Ijo languages", opentypeTag: "IJO ", htmlTag: "ijc" },
  { name: "Ido", opentypeTag: "IDO ", htmlTag: "ido" },
  { name: "Interlingue", opentypeTag: "ILE ", htmlTag: "ile" },
  { name: "Ilokano", opentypeTag: "ILO ", htmlTag: "ilo" },
  { name: "Interlingua", opentypeTag: "INA ", htmlTag: "ina" },
  { name: "Indonesian", opentypeTag: "IND ", htmlTag: "ind" },
  { name: "Ingush", opentypeTag: "ING ", htmlTag: "inh" },
  { name: "Inuktitut", opentypeTag: "INU ", htmlTag: "iku" },
  { name: "Inupiat", opentypeTag: "IPK ", htmlTag: "ipk" },
  { name: "Irish", opentypeTag: "IRI ", htmlTag: "gle" },
  { name: "Irish Traditional", opentypeTag: "IRT ", htmlTag: "gle" },
  { name: "Icelandic", opentypeTag: "ISL ", htmlTag: "isl" },
  { name: "Inari Sami", opentypeTag: "ISM ", htmlTag: "smn" },
  { name: "Italian", opentypeTag: "ITA ", htmlTag: "ita" },
  { name: "Hebrew", opentypeTag: "IWR ", htmlTag: "heb" },
  { name: "Jamaican Creole", opentypeTag: "JAM ", htmlTag: "jam" },
  { name: "Japanese", opentypeTag: "JAN ", htmlTag: "jpn" },
  { name: "Javanese", opentypeTag: "JAV ", htmlTag: "jav" },
  { name: "Lojban", opentypeTag: "JBO ", htmlTag: "jbo" },
  { name: "Krymchak", opentypeTag: "JCT ", htmlTag: "jct" },
  { name: "Yiddish", opentypeTag: "JII ", htmlTag: "yid" },
  { name: "Ladino", opentypeTag: "JUD ", htmlTag: "lad" },
  { name: "Jula", opentypeTag: "JUL ", htmlTag: "dyu" },
  { name: "Kabardian", opentypeTag: "KAB ", htmlTag: "kbd" },
  { name: "Kabyle", opentypeTag: "KAB0", htmlTag: "kab" },
  { name: "Kachchi", opentypeTag: "KAC ", htmlTag: "kfr" },
  { name: "Kalenjin", opentypeTag: "KAL ", htmlTag: "kln" },
  { name: "Kannada", opentypeTag: "KAN ", htmlTag: "kan" },
  { name: "Karachay", opentypeTag: "KAR ", htmlTag: "krc" },
  { name: "Georgian", opentypeTag: "KAT ", htmlTag: "kat" },
  { name: "Kazakh", opentypeTag: "KAZ ", htmlTag: "kaz" },
  { name: "Makonde", opentypeTag: "KDE ", htmlTag: "kde" },
  { name: "Kabuverdianu (Crioulo)", opentypeTag: "KEA ", htmlTag: "kea" },
  { name: "Kebena", opentypeTag: "KEB ", htmlTag: "ktb" },
  { name: "Kekchi", opentypeTag: "KEK ", htmlTag: "kek" },
  { name: "Khutsuri Georgian", opentypeTag: "KGE ", htmlTag: "kat" },
  { name: "Khakass", opentypeTag: "KHA ", htmlTag: "kjh" },
  { name: "Khanty-Kazim", opentypeTag: "KHK ", htmlTag: "kca" },
  { name: "Khmer", opentypeTag: "KHM ", htmlTag: "khm" },
  { name: "Khanty-Shurishkar", opentypeTag: "KHS ", htmlTag: "kca" },
  { name: "Khamti Shan", opentypeTag: "KHT ", htmlTag: "kht" },
  { name: "Khanty-Vakhi", opentypeTag: "KHV ", htmlTag: "kca" },
  { name: "Khowar", opentypeTag: "KHW ", htmlTag: "khw" },
  { name: "Kikuyu (Gikuyu)", opentypeTag: "KIK ", htmlTag: "kik" },
  { name: "Kirghiz (Kyrgyz)", opentypeTag: "KIR ", htmlTag: "kir" },
  { name: "Kisii", opentypeTag: "KIS ", htmlTag: "kqs" },
  { name: "Kirmanjki", opentypeTag: "KIU ", htmlTag: "kiu" },
  { name: "Southern Kiwai", opentypeTag: "KJD ", htmlTag: "kjd" },
  { name: "Eastern Pwo Karen", opentypeTag: "KJP ", htmlTag: "kjp" },
  { name: "Bumthangkha", opentypeTag: "KJZ ", htmlTag: "kjz" },
  { name: "Kokni", opentypeTag: "KKN ", htmlTag: "kex" },
  { name: "Kalmyk", opentypeTag: "KLM ", htmlTag: "xal" },
  { name: "Kamba", opentypeTag: "KMB ", htmlTag: "kam" },
  { name: "Kumaoni", opentypeTag: "KMN ", htmlTag: "kfy" },
  { name: "Komo", opentypeTag: "KMO ", htmlTag: "kmw" },
  { name: "Komso", opentypeTag: "KMS ", htmlTag: "kxc" },
  { name: "Khorasani Turkic", opentypeTag: "KMZ ", htmlTag: "kmz" },
  { name: "Kanuri", opentypeTag: "KNR ", htmlTag: "kau" },
  { name: "Kodagu", opentypeTag: "KOD ", htmlTag: "kfa" },
  { name: "Korean Old Hangul", opentypeTag: "KOH ", htmlTag: "okm" },
  { name: "Konkani", opentypeTag: "KOK ", htmlTag: "kok" },
  { name: "Kikongo", opentypeTag: "KON ", htmlTag: "ktu" },
  { name: "Komi", opentypeTag: "KOM ", htmlTag: "kom" },
  { name: "Kongo", opentypeTag: "KON0", htmlTag: "kon" },
  { name: "Komi-Permyak", opentypeTag: "KOP ", htmlTag: "koi" },
  { name: "Korean", opentypeTag: "KOR ", htmlTag: "kor" },
  { name: "Kosraean", opentypeTag: "KOS ", htmlTag: "kos" },
  { name: "Komi-Zyrian", opentypeTag: "KOZ ", htmlTag: "kpv" },
  { name: "Kpelle", opentypeTag: "KPL ", htmlTag: "kpe" },
  { name: "Krio", opentypeTag: "KRI ", htmlTag: "kri" },
  { name: "Karakalpak", opentypeTag: "KRK ", htmlTag: "kaa" },
  { name: "Karelian", opentypeTag: "KRL ", htmlTag: "krl" },
  { name: "Karaim", opentypeTag: "KRM ", htmlTag: "kdr" },
  { name: "Karen", opentypeTag: "KRN ", htmlTag: "kar" },
  { name: "Koorete", opentypeTag: "KRT ", htmlTag: "kqy" },
  { name: "Kashmiri", opentypeTag: "KSH ", htmlTag: "kas" },
  { name: "Ripuarian", opentypeTag: "KSH0", htmlTag: "ksh" },
  { name: "Khasi", opentypeTag: "KSI ", htmlTag: "kha" },
  { name: "Kildin Sami", opentypeTag: "KSM ", htmlTag: "sjd" },
  { name: "S’gaw Karen", opentypeTag: "KSW ", htmlTag: "ksw" },
  { name: "Kuanyama", opentypeTag: "KUA ", htmlTag: "kua" },
  { name: "Kui", opentypeTag: "KUI ", htmlTag: "kxu" },
  { name: "Kulvi", opentypeTag: "KUL ", htmlTag: "kfx" },
  { name: "Kumyk", opentypeTag: "KUM ", htmlTag: "kum" },
  { name: "Kurdish", opentypeTag: "KUR ", htmlTag: "kur" },
  { name: "Kurukh", opentypeTag: "KUU ", htmlTag: "kru" },
  { name: "Kuy", opentypeTag: "KUY ", htmlTag: "kdt" },
  { name: "Koryak", opentypeTag: "KYK ", htmlTag: "kpy" },
  { name: "Western Kayah", opentypeTag: "KYU ", htmlTag: "kyu" },
  { name: "Ladin", opentypeTag: "LAD ", htmlTag: "lld" },
  { name: "Lahuli", opentypeTag: "LAH ", htmlTag: "bfu" },
  { name: "Lak", opentypeTag: "LAK ", htmlTag: "lbe" },
  { name: "Lambani", opentypeTag: "LAM ", htmlTag: "lmn" },
  { name: "Lao", opentypeTag: "LAO ", htmlTag: "lao" },
  { name: "Latin", opentypeTag: "LAT ", htmlTag: "lat" },
  { name: "Laz", opentypeTag: "LAZ ", htmlTag: "lzz" },
  { name: "L-Cree", opentypeTag: "LCR ", htmlTag: "crm" },
  { name: "Ladakhi", opentypeTag: "LDK ", htmlTag: "lbj" },
  { name: "Lezgi", opentypeTag: "LEZ ", htmlTag: "lez" },
  { name: "Ligurian", opentypeTag: "LIJ ", htmlTag: "lij" },
  { name: "Limburgish", opentypeTag: "LIM ", htmlTag: "lim" },
  { name: "Lingala", opentypeTag: "LIN ", htmlTag: "lin" },
  { name: "Lisu", opentypeTag: "LIS ", htmlTag: "lis" },
  { name: "Lampung", opentypeTag: "LJP ", htmlTag: "ljp" },
  { name: "Laki", opentypeTag: "LKI ", htmlTag: "lki" },
  { name: "Low Mari", opentypeTag: "LMA ", htmlTag: "mhr" },
  { name: "Limbu", opentypeTag: "LMB ", htmlTag: "lif" },
  { name: "Lombard", opentypeTag: "LMO ", htmlTag: "lmo" },
  { name: "Lomwe", opentypeTag: "LMW ", htmlTag: "ngl" },
  { name: "Loma", opentypeTag: "LOM ", htmlTag: "lom" },
  { name: "Luri", opentypeTag: "LRC ", htmlTag: "lrc" },
  { name: "Lower Sorbian", opentypeTag: "LSB ", htmlTag: "dsb" },
  { name: "Lule Sami", opentypeTag: "LSM ", htmlTag: "smj" },
  { name: "Lithuanian", opentypeTag: "LTH ", htmlTag: "lit" },
  { name: "Luxembourgish", opentypeTag: "LTZ ", htmlTag: "ltz" },
  { name: "Luba-Lulua", opentypeTag: "LUA ", htmlTag: "lua" },
  { name: "Luba-Katanga", opentypeTag: "LUB ", htmlTag: "lub" },
  { name: "Ganda", opentypeTag: "LUG ", htmlTag: "lug" },
  { name: "Luyia", opentypeTag: "LUH ", htmlTag: "luy" },
  { name: "Luo", opentypeTag: "LUO ", htmlTag: "luo" },
  { name: "Latvian", opentypeTag: "LVI ", htmlTag: "lav" },
  { name: "Madura", opentypeTag: "MAD ", htmlTag: "mad" },
  { name: "Magahi", opentypeTag: "MAG ", htmlTag: "mag" },
  { name: "Marshallese", opentypeTag: "MAH ", htmlTag: "mah" },
  { name: "Majang", opentypeTag: "MAJ ", htmlTag: "mpe" },
  { name: "Makhuwa", opentypeTag: "MAK ", htmlTag: "vmw" },
  { name: "Malayalam", opentypeTag: "MAL ", htmlTag: "mal" },
  { name: "Mam", opentypeTag: "MAM ", htmlTag: "mam" },
  { name: "Mansi", opentypeTag: "MAN ", htmlTag: "mns" },
  { name: "Mapudungun", opentypeTag: "MAP ", htmlTag: "arn" },
  { name: "Marathi", opentypeTag: "MAR ", htmlTag: "mar" },
  { name: "Marwari", opentypeTag: "MAW ", htmlTag: "mwr" },
  { name: "Mbundu", opentypeTag: "MBN ", htmlTag: "kmb" },
  { name: "Mbo", opentypeTag: "MBO ", htmlTag: "mbo" },
  { name: "Manchu", opentypeTag: "MCH ", htmlTag: "mnc" },
  { name: "Moose Cree", opentypeTag: "MCR ", htmlTag: "crm" },
  { name: "Mende", opentypeTag: "MDE ", htmlTag: "men" },
  { name: "Mandar", opentypeTag: "MDR ", htmlTag: "mdr" },
  { name: "Me’en", opentypeTag: "MEN ", htmlTag: "mym" },
  { name: "Meru", opentypeTag: "MER ", htmlTag: "mer" },
  { name: "Pattani Malay", opentypeTag: "MFA ", htmlTag: "mfa" },
  { name: "Morisyen", opentypeTag: "MFE ", htmlTag: "mfe" },
  { name: "Minangkabau", opentypeTag: "MIN ", htmlTag: "min" },
  { name: "Mizo", opentypeTag: "MIZ ", htmlTag: "lus" },
  { name: "Macedonian", opentypeTag: "MKD ", htmlTag: "mkd" },
  { name: "Makasar", opentypeTag: "MKR ", htmlTag: "mak" },
  { name: "Kituba", opentypeTag: "MKW ", htmlTag: "mkw" },
  { name: "Male", opentypeTag: "MLE ", htmlTag: "mdy" },
  { name: "Malagasy", opentypeTag: "MLG ", htmlTag: "mlg" },
  { name: "Malinke", opentypeTag: "MLN ", htmlTag: "mlq" },
  { name: "Malayalam Reformed", opentypeTag: "MLR ", htmlTag: "mal" },
  { name: "Malay", opentypeTag: "MLY ", htmlTag: "msa" },
  { name: "Mandinka", opentypeTag: "MND ", htmlTag: "mnk" },
  { name: "Mongolian", opentypeTag: "MNG ", htmlTag: "mon" },
  { name: "Manipuri", opentypeTag: "MNI ", htmlTag: "mni" },
  { name: "Maninka", opentypeTag: "MNK ", htmlTag: "man" },
  { name: "Manx", opentypeTag: "MNX ", htmlTag: "glv" },
  { name: "Mohawk", opentypeTag: "MOH ", htmlTag: "moh" },
  { name: "Moksha", opentypeTag: "MOK ", htmlTag: "mdf" },
  { name: "Moldavian", opentypeTag: "MOL ", htmlTag: "mol" },
  { name: "Mon", opentypeTag: "MON ", htmlTag: "mnw" },
  { name: "Moroccan", opentypeTag: "MOR ", htmlTag: "ary" },
  { name: "Mossi", opentypeTag: "MOS ", htmlTag: "mos" },
  { name: "Maori", opentypeTag: "MRI ", htmlTag: "mri" },
  { name: "Maithili", opentypeTag: "MTH ", htmlTag: "mai" },
  { name: "Maltese", opentypeTag: "MTS ", htmlTag: "mlt" },
  { name: "Mundari", opentypeTag: "MUN ", htmlTag: "unr" },
  { name: "Muscogee", opentypeTag: "MUS ", htmlTag: "mus" },
  { name: "Mirandese", opentypeTag: "MWL ", htmlTag: "mwl" },
  { name: "Hmong Daw", opentypeTag: "MWW ", htmlTag: "mww" },
  { name: "Mayan", opentypeTag: "MYN ", htmlTag: "myn" },
  { name: "Mazanderani", opentypeTag: "MZN ", htmlTag: "mzn" },
  { name: "Naga-Assamese", opentypeTag: "NAG ", htmlTag: "nag" },
  { name: "Nahuatl", opentypeTag: "NAH ", htmlTag: "nah" },
  { name: "Nanai", opentypeTag: "NAN ", htmlTag: "gld" },
  { name: "Neapolitan", opentypeTag: "NAP ", htmlTag: "nap" },
  { name: "Naskapi", opentypeTag: "NAS ", htmlTag: "nsk" },
  { name: "Nauruan", opentypeTag: "NAU ", htmlTag: "nau" },
  { name: "Navajo", opentypeTag: "NAV ", htmlTag: "nav" },
  { name: "N-Cree", opentypeTag: "NCR ", htmlTag: "csw" },
  { name: "Ndebele", opentypeTag: "NDB ", htmlTag: "nbl" },
  { name: "Ndau", opentypeTag: "NDC ", htmlTag: "ndc" },
  { name: "Ndonga", opentypeTag: "NDG ", htmlTag: "ndo" },
  { name: "Low Saxon", opentypeTag: "NDS ", htmlTag: "nds" },
  { name: "Nepali", opentypeTag: "NEP ", htmlTag: "nep" },
  { name: "Newari", opentypeTag: "NEW ", htmlTag: "new" },
  { name: "Ngbaka", opentypeTag: "NGA ", htmlTag: "nga" },
  { name: "Norway House Cree", opentypeTag: "NHC ", htmlTag: "csw" },
  { name: "Nisi", opentypeTag: "NIS ", htmlTag: "dap" },
  { name: "Niuean", opentypeTag: "NIU ", htmlTag: "niu" },
  { name: "Nyankole", opentypeTag: "NKL ", htmlTag: "nyn" },
  { name: "N’Ko", opentypeTag: "NKO ", htmlTag: "nqo" },
  { name: "Dutch", opentypeTag: "NLD ", htmlTag: "nld" },
  { name: "Nimadi", opentypeTag: "NOE ", htmlTag: "noe" },
  { name: "Nogai", opentypeTag: "NOG ", htmlTag: "nog" },
  { name: "Norwegian", opentypeTag: "NOR ", htmlTag: "nob" },
  { name: "Novial", opentypeTag: "NOV ", htmlTag: "nov" },
  { name: "Northern Sami", opentypeTag: "NSM ", htmlTag: "sme" },
  { name: "Sotho, Northern", opentypeTag: "NSO ", htmlTag: "nso" },
  { name: "Northern Tai", opentypeTag: "NTA ", htmlTag: "nod" },
  { name: "Esperanto", opentypeTag: "NTO ", htmlTag: "epo" },
  { name: "Nyamwezi", opentypeTag: "NYM ", htmlTag: "nym" },
  { name: "Norwegian Nynorsk (Nynorsk, Norwegian)", opentypeTag: "NYN ", htmlTag: "nno" },
  { name: "Mbembe Tigon", opentypeTag: "NZA ", htmlTag: "nza" },
  { name: "Occitan", opentypeTag: "OCI ", htmlTag: "oci" },
  { name: "Oji-Cree", opentypeTag: "OCR ", htmlTag: "ojs" },
  { name: "Ojibway", opentypeTag: "OJB ", htmlTag: "oji" },
  { name: "Odia (formerly Oriya)", opentypeTag: "ORI ", htmlTag: "ori" },
  { name: "Oromo", opentypeTag: "ORO ", htmlTag: "orm" },
  { name: "Ossetian", opentypeTag: "OSS ", htmlTag: "oss" },
  { name: "Palestinian Aramaic", opentypeTag: "PAA ", htmlTag: "sam" },
  { name: "Pangasinan", opentypeTag: "PAG ", htmlTag: "pag" },
  { name: "Pali", opentypeTag: "PAL ", htmlTag: "pli" },
  { name: "Pampangan", opentypeTag: "PAM ", htmlTag: "pam" },
  { name: "Punjabi", opentypeTag: "PAN ", htmlTag: "pan" },
  { name: "Palpa", opentypeTag: "PAP ", htmlTag: "plp" },
  { name: "Papiamentu", opentypeTag: "PAP0", htmlTag: "pap" },
  { name: "Pashto", opentypeTag: "PAS ", htmlTag: "pus" },
  { name: "Palauan", opentypeTag: "PAU ", htmlTag: "pau" },
  { name: "Bouyei", opentypeTag: "PCC ", htmlTag: "pcc" },
  { name: "Picard", opentypeTag: "PCD ", htmlTag: "pcd" },
  { name: "Pennsylvania German", opentypeTag: "PDC ", htmlTag: "pdc" },
  { name: "Polytonic Greek", opentypeTag: "PGR ", htmlTag: "ell" },
  { name: "Phake", opentypeTag: "PHK ", htmlTag: "phk" },
  { name: "Norfolk", opentypeTag: "PIH ", htmlTag: "pih" },
  { name: "Filipino", opentypeTag: "PIL ", htmlTag: "fil" },
  { name: "Palaung", opentypeTag: "PLG ", htmlTag: "pce" },
  { name: "Polish", opentypeTag: "PLK ", htmlTag: "pol" },
  { name: "Piemontese", opentypeTag: "PMS ", htmlTag: "pms" },
  { name: "Western Panjabi", opentypeTag: "PNB ", htmlTag: "pnb" },
  { name: "Pocomchi", opentypeTag: "POH ", htmlTag: "poh" },
  { name: "Pohnpeian", opentypeTag: "PON ", htmlTag: "pon" },
  { name: "Provençal / Old Provençal", opentypeTag: "PRO ", htmlTag: "pro" },
  { name: "Portuguese", opentypeTag: "PTG ", htmlTag: "por" },
  { name: "Western Pwo Karen", opentypeTag: "PWO ", htmlTag: "pwo" },
  { name: "Chin", opentypeTag: "QIN ", htmlTag: "bgr" },
  { name: "K’iche’", opentypeTag: "QUC ", htmlTag: "quc" },
  { name: "Quechua (Bolivia)", opentypeTag: "QUH ", htmlTag: "quh" },
  { name: "Quechua", opentypeTag: "QUZ ", htmlTag: "quz" },
  { name: "Quechua (Ecuador)", opentypeTag: "QVI ", htmlTag: "qvi" },
  { name: "Quechua (Peru)", opentypeTag: "QWH ", htmlTag: "qwh" },
  { name: "Rajasthani", opentypeTag: "RAJ ", htmlTag: "raj" },
  { name: "Rarotongan", opentypeTag: "RAR ", htmlTag: "rar" },
  { name: "Russian Buriat", opentypeTag: "RBU ", htmlTag: "bxr" },
  { name: "R-Cree", opentypeTag: "RCR ", htmlTag: "atj" },
  { name: "Rejang", opentypeTag: "REJ ", htmlTag: "rej" },
  { name: "Riang", opentypeTag: "RIA ", htmlTag: "ria" },
  { name: "Tarifit", opentypeTag: "RIF ", htmlTag: "rif" },
  { name: "Ritarungo", opentypeTag: "RIT ", htmlTag: "rit" },
  { name: "Arakwal", opentypeTag: "RKW ", htmlTag: "rkw" },
  { name: "Romansh", opentypeTag: "RMS ", htmlTag: "roh" },
  { name: "Vlax Romani", opentypeTag: "RMY ", htmlTag: "rmy" },
  { name: "Romanian", opentypeTag: "ROM ", htmlTag: "ron" },
  { name: "Romany", opentypeTag: "ROY ", htmlTag: "rom" },
  { name: "Rusyn", opentypeTag: "RSY ", htmlTag: "rue" },
  { name: "Rotuman", opentypeTag: "RTM ", htmlTag: "rtm" },
  { name: "Kinyarwanda", opentypeTag: "RUA ", htmlTag: "kin" },
  { name: "Rundi", opentypeTag: "RUN ", htmlTag: "run" },
  { name: "Aromanian", opentypeTag: "RUP ", htmlTag: "rup" },
  { name: "Russian", opentypeTag: "RUS ", htmlTag: "rus" },
  { name: "Sadri", opentypeTag: "SAD ", htmlTag: "sck" },
  { name: "Sanskrit", opentypeTag: "SAN ", htmlTag: "san" },
  { name: "Sasak", opentypeTag: "SAS ", htmlTag: "sas" },
  { name: "Santali", opentypeTag: "SAT ", htmlTag: "sat" },
  { name: "Sayisi", opentypeTag: "SAY ", htmlTag: "chp" },
  { name: "Sicilian", opentypeTag: "SCN ", htmlTag: "scn" },
  { name: "Scots", opentypeTag: "SCO ", htmlTag: "sco" },
  { name: "Sekota", opentypeTag: "SEK ", htmlTag: "xan" },
  { name: "Selkup", opentypeTag: "SEL ", htmlTag: "sel" },
  { name: "Old Irish", opentypeTag: "SGA ", htmlTag: "sga" },
  { name: "Sango", opentypeTag: "SGO ", htmlTag: "sag" },
  { name: "Samogitian", opentypeTag: "SGS ", htmlTag: "sgs" },
  { name: "Tachelhit", opentypeTag: "SHI ", htmlTag: "shi" },
  { name: "Shan", opentypeTag: "SHN ", htmlTag: "shn" },
  { name: "Sibe", opentypeTag: "SIB ", htmlTag: "sjo" },
  { name: "Sidamo", opentypeTag: "SID ", htmlTag: "sid" },
  { name: "Silte Gurage", opentypeTag: "SIG ", htmlTag: "xst" },
  { name: "Skolt Sami", opentypeTag: "SKS ", htmlTag: "sms" },
  { name: "Slovak", opentypeTag: "SKY ", htmlTag: "slk" },
  { name: "North Slavey", opentypeTag: "SCS ", htmlTag: "scs" },
  { name: "Slavey", opentypeTag: "SLA ", htmlTag: "scs" },
  { name: "Slovenian", opentypeTag: "SLV ", htmlTag: "slv" },
  { name: "Somali", opentypeTag: "SML ", htmlTag: "som" },
  { name: "Samoan", opentypeTag: "SMO ", htmlTag: "smo" },
  { name: "Sena", opentypeTag: "SNA ", htmlTag: "seh" },
  { name: "Shona", opentypeTag: "SNA0", htmlTag: "sna" },
  { name: "Sindhi", opentypeTag: "SND ", htmlTag: "snd" },
  { name: "Sinhala (Sinhalese)", opentypeTag: "SNH ", htmlTag: "sin" },
  { name: "Soninke", opentypeTag: "SNK ", htmlTag: "snk" },
  { name: "Sodo Gurage", opentypeTag: "SOG ", htmlTag: "gru" },
  { name: "Songe", opentypeTag: "SOP ", htmlTag: "sop" },
  { name: "Sotho, Southern", opentypeTag: "SOT ", htmlTag: "sot" },
  { name: "Albanian", opentypeTag: "SQI ", htmlTag: "sqi" },
  { name: "Serbian", opentypeTag: "SRB ", htmlTag: "srp" },
  { name: "Sardinian", opentypeTag: "SRD ", htmlTag: "srd" },
  { name: "Saraiki", opentypeTag: "SRK ", htmlTag: "skr" },
  { name: "Serer", opentypeTag: "SRR ", htmlTag: "srr" },
  { name: "South Slavey", opentypeTag: "SSL ", htmlTag: "xsl" },
  { name: "Southern Sami", opentypeTag: "SSM ", htmlTag: "sma" },
  { name: "Saterland Frisian", opentypeTag: "STQ ", htmlTag: "stq" },
  { name: "Sukuma", opentypeTag: "SUK ", htmlTag: "suk" },
  { name: "Sundanese", opentypeTag: "SUN ", htmlTag: "sun" },
  { name: "Suri", opentypeTag: "SUR ", htmlTag: "suq" },
  { name: "Svan", opentypeTag: "SVA ", htmlTag: "sva" },
  { name: "Swedish", opentypeTag: "SVE ", htmlTag: "swe" },
  { name: "Swadaya Aramaic", opentypeTag: "SWA ", htmlTag: "aii" },
  { name: "Swahili", opentypeTag: "SWK ", htmlTag: "swa" },
  { name: "Swati", opentypeTag: "SWZ ", htmlTag: "ssw" },
  { name: "Sutu", opentypeTag: "SXT ", htmlTag: "ngo" },
  { name: "Upper Saxon", opentypeTag: "SXU ", htmlTag: "sxu" },
  { name: "Sylheti", opentypeTag: "SYL ", htmlTag: "syl" },
  { name: "Syriac", opentypeTag: "SYR ", htmlTag: "aii" },
  { name: "Syriac, Estrangela script-variant (equivalent to ISO 15924 'Syre')", opentypeTag: "SYRE", htmlTag: "syc" },
  { name: "Syriac, Western script-variant (equivalent to ISO 15924 'Syrj')", opentypeTag: "SYRJ", htmlTag: "syc" },
  { name: "Syriac, Eastern script-variant (equivalent to ISO 15924 'Syrn')", opentypeTag: "SYRN", htmlTag: "syc" },
  { name: "Silesian", opentypeTag: "SZL ", htmlTag: "szl" },
  { name: "Tabasaran", opentypeTag: "TAB ", htmlTag: "tab" },
  { name: "Tajiki", opentypeTag: "TAJ ", htmlTag: "tgk" },
  { name: "Tamil", opentypeTag: "TAM ", htmlTag: "tam" },
  { name: "Tatar", opentypeTag: "TAT ", htmlTag: "tat" },
  { name: "TH-Cree", opentypeTag: "TCR ", htmlTag: "cwd" },
  { name: "Dehong Dai", opentypeTag: "TDD ", htmlTag: "tdd" },
  { name: "Telugu", opentypeTag: "TEL ", htmlTag: "tel" },
  { name: "Tetum", opentypeTag: "TET ", htmlTag: "tet" },
  { name: "Tagalog", opentypeTag: "TGL ", htmlTag: "tgl" },
  { name: "Tongan", opentypeTag: "TGN ", htmlTag: "ton" },
  { name: "Tigre", opentypeTag: "TGR ", htmlTag: "tig" },
  { name: "Tigrinya", opentypeTag: "TGY ", htmlTag: "tir" },
  { name: "Thai", opentypeTag: "THA ", htmlTag: "tha" },
  { name: "Tahitian", opentypeTag: "THT ", htmlTag: "tah" },
  { name: "Tibetan", opentypeTag: "TIB ", htmlTag: "bod" },
  { name: "Tiv", opentypeTag: "TIV ", htmlTag: "tiv" },
  { name: "Turkmen", opentypeTag: "TKM ", htmlTag: "tuk" },
  { name: "Tamashek", opentypeTag: "TMH ", htmlTag: "tmh" },
  { name: "Temne", opentypeTag: "TMN ", htmlTag: "tem" },
  { name: "Tswana", opentypeTag: "TNA ", htmlTag: "tsn" },
  { name: "Tundra Nenets", opentypeTag: "TNE ", htmlTag: "enh" },
  { name: "Tonga", opentypeTag: "TNG ", htmlTag: "toi" },
  { name: "Todo", opentypeTag: "TOD ", htmlTag: "xal" },
  { name: "Toma", opentypeTag: "TOD0", htmlTag: "tod" },
  { name: "Tok Pisin", opentypeTag: "TPI ", htmlTag: "tpi" },
  { name: "Turkish", opentypeTag: "TRK ", htmlTag: "tur" },
  { name: "Tsonga", opentypeTag: "TSG ", htmlTag: "tso" },
  { name: "Tshangla", opentypeTag: "TSJ ", htmlTag: "tsj" },
  { name: "Turoyo Aramaic", opentypeTag: "TUA ", htmlTag: "tru" },
  { name: "Tulu", opentypeTag: "TUM ", htmlTag: "tum" },
  { name: "Tumbuka", opentypeTag: "TUL ", htmlTag: "tcy" },
  { name: "Tuvin", opentypeTag: "TUV ", htmlTag: "tyv" },
  { name: "Tuvalu", opentypeTag: "TVL ", htmlTag: "tvl" },
  { name: "Twi", opentypeTag: "TWI ", htmlTag: "aka" },
  { name: "Tày", opentypeTag: "TYZ ", htmlTag: "tyz" },
  { name: "Tamazight", opentypeTag: "TZM ", htmlTag: "tzm" },
  { name: "Tzotzil", opentypeTag: "TZO ", htmlTag: "tzo" },
  { name: "Udmurt", opentypeTag: "UDM ", htmlTag: "udm" },
  { name: "Ukrainian", opentypeTag: "UKR ", htmlTag: "ukr" },
  { name: "Umbundu", opentypeTag: "UMB ", htmlTag: "umb" },
  { name: "Urdu", opentypeTag: "URD ", htmlTag: "urd" },
  { name: "Upper Sorbian", opentypeTag: "USB ", htmlTag: "hsb" },
  { name: "Uyghur", opentypeTag: "UYG ", htmlTag: "uig" },
  { name: "Uzbek", opentypeTag: "UZB ", htmlTag: "uzb" },
  { name: "Venetian", opentypeTag: "VEC ", htmlTag: "vec" },
  { name: "Venda", opentypeTag: "VEN ", htmlTag: "ven" },
  { name: "Vietnamese", opentypeTag: "VIT ", htmlTag: "vie" },
  { name: "Volapük", opentypeTag: "VOL ", htmlTag: "vol" },
  { name: "Võro", opentypeTag: "VRO ", htmlTag: "vro" },
  { name: "Wa", opentypeTag: "WA", htmlTag: "wbm" },
  { name: "Wagdi", opentypeTag: "WAG ", htmlTag: "wbr" },
  { name: "Waray-Waray", opentypeTag: "WAR ", htmlTag: "war" },
  { name: "West-Cree", opentypeTag: "WCR ", htmlTag: "crk" },
  { name: "Welsh", opentypeTag: "WEL ", htmlTag: "cym" },
  { name: "Walloon", opentypeTag: "WLN ", htmlTag: "wln" },
  { name: "Wolof", opentypeTag: "WLF ", htmlTag: "wol" },
  { name: "Mewati", opentypeTag: "WTM ", htmlTag: "wtm" },
  { name: "Lü", opentypeTag: "XBD ", htmlTag: "khb" },
  { name: "Khengkha", opentypeTag: "XKF ", htmlTag: "xkf" },
  { name: "Xhosa", opentypeTag: "XHS ", htmlTag: "xho" },
  { name: "Minjangbal", opentypeTag: "XJB ", htmlTag: "xjb" },
  { name: "Soga", opentypeTag: "XOG ", htmlTag: "xog" },
  { name: "Kpelle (Liberia)", opentypeTag: "XPE ", htmlTag: "xpe" },
  { name: "Sakha", opentypeTag: "YAK ", htmlTag: "sah" },
  { name: "Yao", opentypeTag: "YAO ", htmlTag: "yao" },
  { name: "Yapese", opentypeTag: "YAP ", htmlTag: "yap" },
  { name: "Yoruba", opentypeTag: "YBA ", htmlTag: "yor" },
  { name: "Y-Cree", opentypeTag: "YCR ", htmlTag: "cre" },
  { name: "Yi Modern", opentypeTag: "YIM ", htmlTag: "iii" },
  { name: "Zealandic", opentypeTag: "ZEA ", htmlTag: "zea" },
  { name: "Standard Moroccan Tamazight", opentypeTag: "ZGH ", htmlTag: "zgh" },
  { name: "Zhuang", opentypeTag: "ZHA ", htmlTag: "zha" },
  { name: "Chinese, Hong Kong SAR", opentypeTag: "ZHH ", htmlTag: "zho" },
  { name: "Chinese Phonetic", opentypeTag: "ZHP ", htmlTag: "zho" },
  { name: "Chinese Simplified", opentypeTag: "ZHS ", htmlTag: "zho" },
  { name: "Chinese Traditional", opentypeTag: "ZHT ", htmlTag: "zho" },
  { name: "Zande", opentypeTag: "ZND ", htmlTag: "zne" },
  { name: "Zulu", opentypeTag: "ZUL ", htmlTag: "zul" },
  { name: "Zazaki", opentypeTag: "ZZA ", htmlTag: "zza" },
];
