module.exports = [
  { tag: "ABA ", name: "Abaza" },
  { tag: "ABK ", name: "Abkhazian" },
  { tag: "ACH ", name: "Acholi" },
  { tag: "ACR ", name: "Achi" },
  { tag: "ADY ", name: "Adyghe" },
  { tag: "AFK ", name: "Afrikaans" },
  { tag: "AFR ", name: "Afar" },
  { tag: "AGW ", name: "Agaw" },
  { tag: "AIO ", name: "Aiton" },
  { tag: "AKA ", name: "Akan" },
  { tag: "ALS ", name: "Alsatian" },
  { tag: "ALT ", name: "Altai" },
  { tag: "AMH ", name: "Amharic" },
  { tag: "ANG ", name: "Anglo-Saxon" },
  { tag: "APPH", name: "Phonetic transcription—Americanist conventions" },
  { tag: "ARA ", name: "Arabic" },
  { tag: "ARG ", name: "Aragonese" },
  { tag: "ARI ", name: "Aari" },
  { tag: "ARK ", name: "Rakhine" },
  { tag: "ASM ", name: "Assamese" },
  { tag: "AST ", name: "Asturian" },
  { tag: "ATH ", name: "Athapaskan" },
  { tag: "AVR ", name: "Avar" },
  { tag: "AWA ", name: "Awadhi" },
  { tag: "AYM ", name: "Aymara" },
  { tag: "AZB ", name: "Torki" },
  { tag: "AZE ", name: "Azerbaijani" },
  { tag: "BAD ", name: "Badaga" },
  { tag: "BAD0", name: "Banda" },
  { tag: "BAG ", name: "Baghelkhandi" },
  { tag: "BAL ", name: "Balkar" },
  { tag: "BAN ", name: "Balinese" },
  { tag: "BAR ", name: "Bavarian" },
  { tag: "BAU ", name: "Baulé" },
  { tag: "BBC ", name: "Batak Toba" },
  { tag: "BBR ", name: "Berber" },
  { tag: "BCH ", name: "Bench" },
  { tag: "BCR ", name: "Bible Cree" },
  { tag: "BDY ", name: "Bandjalang" },
  { tag: "BEL ", name: "Belarussian" },
  { tag: "BEM ", name: "Bemba" },
  { tag: "BEN ", name: "Bengali" },
  { tag: "BGC ", name: "Haryanvi" },
  { tag: "BGQ ", name: "Bagri" },
  { tag: "BGR ", name: "Bulgarian" },
  { tag: "BHI ", name: "Bhili" },
  { tag: "BHO ", name: "Bhojpuri" },
  { tag: "BIK ", name: "Bikol" },
  { tag: "BIL ", name: "Bilen" },
  { tag: "BIS ", name: "Bislama" },
  { tag: "BJJ ", name: "Kanauji" },
  { tag: "BKF ", name: "Blackfoot" },
  { tag: "BLI ", name: "Baluchi" },
  { tag: "BLK ", name: "Pa’o Karen" },
  { tag: "BLN ", name: "Balante" },
  { tag: "BLT ", name: "Balti" },
  { tag: "BMB ", name: "Bambara (Bamanankan)" },
  { tag: "BML ", name: "Bamileke" },
  { tag: "BOS ", name: "Bosnian" },
  { tag: "BPY ", name: "Bishnupriya Manipuri" },
  { tag: "BRE ", name: "Breton" },
  { tag: "BRH ", name: "Brahui" },
  { tag: "BRI ", name: "Braj Bhasha" },
  { tag: "BRM ", name: "Burmese" },
  { tag: "BRX ", name: "Bodo" },
  { tag: "BSH ", name: "Bashkir" },
  { tag: "BSK ", name: "Burushaski" },
  { tag: "BTI ", name: "Beti" },
  { tag: "BTS ", name: "Batak Simalungun" },
  { tag: "BUG ", name: "Bugis" },
  { tag: "BYV ", name: "Medumba" },
  { tag: "CAK ", name: "Kaqchikel" },
  { tag: "CAT ", name: "Catalan" },
  { tag: "CBK ", name: "Zamboanga Chavacano" },
  { tag: "CCHN", name: "Chinantec" },
  { tag: "CEB ", name: "Cebuano" },
  { tag: "CHE ", name: "Chechen" },
  { tag: "CHG ", name: "Chaha Gurage" },
  { tag: "CHH ", name: "Chattisgarhi" },
  { tag: "CHI ", name: "Chichewa (Chewa, Nyanja)" },
  { tag: "CHK ", name: "Chukchi" },
  { tag: "CHK0", name: "Chuukese" },
  { tag: "CHO ", name: "Choctaw" },
  { tag: "CHP ", name: "Chipewyan" },
  { tag: "CHR ", name: "Cherokee" },
  { tag: "CHA ", name: "Chamorro" },
  { tag: "CHU ", name: "Chuvash" },
  { tag: "CHY ", name: "Cheyenne" },
  { tag: "CGG ", name: "Chiga" },
  { tag: "CJA ", name: "Western Cham" },
  { tag: "CJM ", name: "Eastern Cham" },
  { tag: "CMR ", name: "Comorian" },
  { tag: "COP ", name: "Coptic" },
  { tag: "COR ", name: "Cornish" },
  { tag: "COS ", name: "Corsican" },
  { tag: "CPP ", name: "Creoles" },
  { tag: "CRE ", name: "Cree" },
  { tag: "CRR ", name: "Carrier" },
  { tag: "CRT ", name: "Crimean Tatar" },
  { tag: "CSB ", name: "Kashubian" },
  { tag: "CSL ", name: "Church Slavonic" },
  { tag: "CSY ", name: "Czech" },
  { tag: "CTG ", name: "Chittagonian" },
  { tag: "CUK ", name: "San Blas Kuna" },
  { tag: "DAN ", name: "Danish" },
  { tag: "DAR ", name: "Dargwa" },
  { tag: "DAX ", name: "Dayi" },
  { tag: "DCR ", name: "Woods Cree" },
  { tag: "DEU ", name: "German" },
  { tag: "DGO ", name: "Dogri" },
  { tag: "DGR ", name: "Dogri" },
  { tag: "DHG ", name: "Dhangu" },
  { tag: "DHV  (deprecated)", name: "Divehi (Dhivehi, Maldivian)" },
  { tag: "DIQ ", name: "Dimli" },
  { tag: "DIV ", name: "Divehi (Dhivehi, Maldivian)" },
  { tag: "DJR ", name: "Zarma" },
  { tag: "DJR0", name: "Djambarrpuyngu" },
  { tag: "DNG ", name: "Dangme" },
  { tag: "DNJ ", name: "Dan" },
  { tag: "DNK ", name: "Dinka" },
  { tag: "DRI ", name: "Dari" },
  { tag: "DUJ ", name: "Dhuwal" },
  { tag: "DUN ", name: "Dungan" },
  { tag: "DZN ", name: "Dzongkha" },
  { tag: "EBI ", name: "Ebira" },
  { tag: "ECR ", name: "Eastern Cree" },
  { tag: "EDO ", name: "Edo" },
  { tag: "EFI ", name: "Efik" },
  { tag: "ELL ", name: "Greek" },
  { tag: "EMK ", name: "Eastern Maninkakan" },
  { tag: "ENG ", name: "English" },
  { tag: "ERZ ", name: "Erzya" },
  { tag: "ESP ", name: "Spanish" },
  { tag: "ESU ", name: "Central Yupik" },
  { tag: "ETI ", name: "Estonian" },
  { tag: "EUQ ", name: "Basque" },
  { tag: "EVK ", name: "Evenki" },
  { tag: "EVN ", name: "Even" },
  { tag: "EWE ", name: "Ewe" },
  { tag: "FAN ", name: "French Antillean" },
  { tag: "FAN0", name: "Fang" },
  { tag: "FAR ", name: "Persian" },
  { tag: "FAT ", name: "Fanti" },
  { tag: "FIN ", name: "Finnish" },
  { tag: "FJI ", name: "Fijian" },
  { tag: "FLE ", name: "Dutch (Flemish)" },
  { tag: "FMP ", name: "Fe’fe’" },
  { tag: "FNE ", name: "Forest Nenets" },
  { tag: "FON ", name: "Fon" },
  { tag: "FOS ", name: "Faroese" },
  { tag: "FRA ", name: "French" },
  { tag: "FRC ", name: "Cajun French" },
  { tag: "FRI ", name: "Frisian" },
  { tag: "FRL ", name: "Friulian" },
  { tag: "FRP ", name: "Arpitan" },
  { tag: "FTA ", name: "Futa" },
  { tag: "FUL ", name: "Fulah" },
  { tag: "FUV ", name: "Nigerian Fulfulde" },
  { tag: "GAD ", name: "Ga" },
  { tag: "GAE ", name: "Scottish Gaelic (Gaelic)" },
  { tag: "GAG ", name: "Gagauz" },
  { tag: "GAL ", name: "Galician" },
  { tag: "GAR ", name: "Garshuni" },
  { tag: "GAW ", name: "Garhwali" },
  { tag: "GEZ ", name: "Geez" },
  { tag: "GIH ", name: "Githabul" },
  { tag: "GIL ", name: "Gilyak" },
  { tag: "GIL0", name: "Kiribati (Gilbertese)" },
  { tag: "GKP ", name: "Kpelle (Guinea)" },
  { tag: "GLK ", name: "Gilaki" },
  { tag: "GMZ ", name: "Gumuz" },
  { tag: "GNN ", name: "Gumatj" },
  { tag: "GOG ", name: "Gogo" },
  { tag: "GON ", name: "Gondi" },
  { tag: "GRN ", name: "Greenlandic" },
  { tag: "GRO ", name: "Garo" },
  { tag: "GUA ", name: "Guarani" },
  { tag: "GUC ", name: "Wayuu" },
  { tag: "GUF ", name: "Gupapuyngu" },
  { tag: "GUJ ", name: "Gujarati" },
  { tag: "GUZ ", name: "Gusii" },
  { tag: "HAI ", name: "Haitian (Haitian Creole)" },
  { tag: "HAL ", name: "Halam (Falam Chin)" },
  { tag: "HAR ", name: "Harauti" },
  { tag: "HAU ", name: "Hausa" },
  { tag: "HAW ", name: "Hawaiian" },
  { tag: "HAY ", name: "Haya" },
  { tag: "HAZ ", name: "Hazaragi" },
  { tag: "HBN ", name: "Hammer-Banna" },
  { tag: "HER ", name: "Herero" },
  { tag: "HIL ", name: "Hiligaynon" },
  { tag: "HIN ", name: "Hindi" },
  { tag: "HMA ", name: "High Mari" },
  { tag: "HMN ", name: "Hmong" },
  { tag: "HMO ", name: "Hiri Motu" },
  { tag: "HND ", name: "Hindko" },
  { tag: "HO", name: "Ho" },
  { tag: "HRI ", name: "Harari" },
  { tag: "HRV ", name: "Croatian" },
  { tag: "HUN ", name: "Hungarian" },
  { tag: "HYE ", name: "Armenian" },
  { tag: "HYE0", name: "Armenian East" },
  { tag: "IBA ", name: "Iban" },
  { tag: "IBB ", name: "Ibibio" },
  { tag: "IBO ", name: "Igbo" },
  { tag: "IJO ", name: "Ijo languages" },
  { tag: "IDO ", name: "Ido" },
  { tag: "ILE ", name: "Interlingue" },
  { tag: "ILO ", name: "Ilokano" },
  { tag: "INA ", name: "Interlingua" },
  { tag: "IND ", name: "Indonesian" },
  { tag: "ING ", name: "Ingush" },
  { tag: "INU ", name: "Inuktitut" },
  { tag: "IPK ", name: "Inupiat" },
  { tag: "IPPH", name: "Phonetic transcription—IPA conventions" },
  { tag: "IRI ", name: "Irish" },
  { tag: "IRT ", name: "Irish Traditional" },
  { tag: "ISL ", name: "Icelandic" },
  { tag: "ISM ", name: "Inari Sami" },
  { tag: "ITA ", name: "Italian" },
  { tag: "IWR ", name: "Hebrew" },
  { tag: "JAM ", name: "Jamaican Creole" },
  { tag: "JAN ", name: "Japanese" },
  { tag: "JAV ", name: "Javanese" },
  { tag: "JBO ", name: "Lojban" },
  { tag: "JCT ", name: "Krymchak" },
  { tag: "JII ", name: "Yiddish" },
  { tag: "JUD ", name: "Ladino" },
  { tag: "JUL ", name: "Jula" },
  { tag: "KAB ", name: "Kabardian" },
  { tag: "KAB0", name: "Kabyle" },
  { tag: "KAC ", name: "Kachchi" },
  { tag: "KAL ", name: "Kalenjin" },
  { tag: "KAN ", name: "Kannada" },
  { tag: "KAR ", name: "Karachay" },
  { tag: "KAT ", name: "Georgian" },
  { tag: "KAZ ", name: "Kazakh" },
  { tag: "KDE ", name: "Makonde" },
  { tag: "KEA ", name: "Kabuverdianu (Crioulo)" },
  { tag: "KEB ", name: "Kebena" },
  { tag: "KEK ", name: "Kekchi" },
  { tag: "KGE ", name: "Khutsuri Georgian" },
  { tag: "KHA ", name: "Khakass" },
  { tag: "KHK ", name: "Khanty-Kazim" },
  { tag: "KHM ", name: "Khmer" },
  { tag: "KHS ", name: "Khanty-Shurishkar" },
  { tag: "KHT ", name: "Khamti Shan" },
  { tag: "KHV ", name: "Khanty-Vakhi" },
  { tag: "KHW ", name: "Khowar" },
  { tag: "KIK ", name: "Kikuyu (Gikuyu)" },
  { tag: "KIR ", name: "Kirghiz (Kyrgyz)" },
  { tag: "KIS ", name: "Kisii" },
  { tag: "KIU ", name: "Kirmanjki" },
  { tag: "KJD ", name: "Southern Kiwai" },
  { tag: "KJP ", name: "Eastern Pwo Karen" },
  { tag: "KJZ ", name: "Bumthangkha" },
  { tag: "KKN ", name: "Kokni" },
  { tag: "KLM ", name: "Kalmyk" },
  { tag: "KMB ", name: "Kamba" },
  { tag: "KMN ", name: "Kumaoni" },
  { tag: "KMO ", name: "Komo" },
  { tag: "KMS ", name: "Komso" },
  { tag: "KMZ ", name: "Khorasani Turkic" },
  { tag: "KNR ", name: "Kanuri" },
  { tag: "KOD ", name: "Kodagu" },
  { tag: "KOH ", name: "Korean Old Hangul" },
  { tag: "KOK ", name: "Konkani" },
  { tag: "KON ", name: "Kikongo" },
  { tag: "KOM ", name: "Komi" },
  { tag: "KON0", name: "Kongo" },
  { tag: "KOP ", name: "Komi-Permyak" },
  { tag: "KOR ", name: "Korean" },
  { tag: "KOS ", name: "Kosraean" },
  { tag: "KOZ ", name: "Komi-Zyrian" },
  { tag: "KPL ", name: "Kpelle" },
  { tag: "KRI ", name: "Krio" },
  { tag: "KRK ", name: "Karakalpak" },
  { tag: "KRL ", name: "Karelian" },
  { tag: "KRM ", name: "Karaim" },
  { tag: "KRN ", name: "Karen" },
  { tag: "KRT ", name: "Koorete" },
  { tag: "KSH ", name: "Kashmiri" },
  { tag: "KSH0", name: "Ripuarian" },
  { tag: "KSI ", name: "Khasi" },
  { tag: "KSM ", name: "Kildin Sami" },
  { tag: "KSW ", name: "S’gaw Karen" },
  { tag: "KUA ", name: "Kuanyama" },
  { tag: "KUI ", name: "Kui" },
  { tag: "KUL ", name: "Kulvi" },
  { tag: "KUM ", name: "Kumyk" },
  { tag: "KUR ", name: "Kurdish" },
  { tag: "KUU ", name: "Kurukh" },
  { tag: "KUY ", name: "Kuy" },
  { tag: "KYK ", name: "Koryak" },
  { tag: "KYU ", name: "Western Kayah" },
  { tag: "LAD ", name: "Ladin" },
  { tag: "LAH ", name: "Lahuli" },
  { tag: "LAK ", name: "Lak" },
  { tag: "LAM ", name: "Lambani" },
  { tag: "LAO ", name: "Lao" },
  { tag: "LAT ", name: "Latin" },
  { tag: "LAZ ", name: "Laz" },
  { tag: "LCR ", name: "L-Cree" },
  { tag: "LDK ", name: "Ladakhi" },
  { tag: "LEZ ", name: "Lezgi" },
  { tag: "LIJ ", name: "Ligurian" },
  { tag: "LIM ", name: "Limburgish" },
  { tag: "LIN ", name: "Lingala" },
  { tag: "LIS ", name: "Lisu" },
  { tag: "LJP ", name: "Lampung" },
  { tag: "LKI ", name: "Laki" },
  { tag: "LMA ", name: "Low Mari" },
  { tag: "LMB ", name: "Limbu" },
  { tag: "LMO ", name: "Lombard" },
  { tag: "LMW ", name: "Lomwe" },
  { tag: "LOM ", name: "Loma" },
  { tag: "LRC ", name: "Luri" },
  { tag: "LSB ", name: "Lower Sorbian" },
  { tag: "LSM ", name: "Lule Sami" },
  { tag: "LTH ", name: "Lithuanian" },
  { tag: "LTZ ", name: "Luxembourgish" },
  { tag: "LUA ", name: "Luba-Lulua" },
  { tag: "LUB ", name: "Luba-Katanga" },
  { tag: "LUG ", name: "Ganda" },
  { tag: "LUH ", name: "Luyia" },
  { tag: "LUO ", name: "Luo" },
  { tag: "LVI ", name: "Latvian" },
  { tag: "MAD ", name: "Madura" },
  { tag: "MAG ", name: "Magahi" },
  { tag: "MAH ", name: "Marshallese" },
  { tag: "MAJ ", name: "Majang" },
  { tag: "MAK ", name: "Makhuwa" },
  { tag: "MAL ", name: "Malayalam" },
  { tag: "MAM ", name: "Mam" },
  { tag: "MAN ", name: "Mansi" },
  { tag: "MAP ", name: "Mapudungun" },
  { tag: "MAR ", name: "Marathi" },
  { tag: "MAW ", name: "Marwari" },
  { tag: "MBN ", name: "Mbundu" },
  { tag: "MBO ", name: "Mbo" },
  { tag: "MCH ", name: "Manchu" },
  { tag: "MCR ", name: "Moose Cree" },
  { tag: "MDE ", name: "Mende" },
  { tag: "MDR ", name: "Mandar" },
  { tag: "MEN ", name: "Me’en" },
  { tag: "MER ", name: "Meru" },
  { tag: "MFA ", name: "Pattani Malay" },
  { tag: "MFE ", name: "Morisyen" },
  { tag: "MIN ", name: "Minangkabau" },
  { tag: "MIZ ", name: "Mizo" },
  { tag: "MKD ", name: "Macedonian" },
  { tag: "MKR ", name: "Makasar" },
  { tag: "MKW ", name: "Kituba" },
  { tag: "MLE ", name: "Male" },
  { tag: "MLG ", name: "Malagasy" },
  { tag: "MLN ", name: "Malinke" },
  { tag: "MLR ", name: "Malayalam Reformed" },
  { tag: "MLY ", name: "Malay" },
  { tag: "MND ", name: "Mandinka" },
  { tag: "MNG ", name: "Mongolian" },
  { tag: "MNI ", name: "Manipuri" },
  { tag: "MNK ", name: "Maninka" },
  { tag: "MNX ", name: "Manx" },
  { tag: "MOH ", name: "Mohawk" },
  { tag: "MOK ", name: "Moksha" },
  { tag: "MOL ", name: "Moldavian" },
  { tag: "MON ", name: "Mon" },
  { tag: "MOR ", name: "Moroccan" },
  { tag: "MOS ", name: "Mossi" },
  { tag: "MRI ", name: "Maori" },
  { tag: "MTH ", name: "Maithili" },
  { tag: "MTS ", name: "Maltese" },
  { tag: "MUN ", name: "Mundari" },
  { tag: "MUS ", name: "Muscogee" },
  { tag: "MWL ", name: "Mirandese" },
  { tag: "MWW ", name: "Hmong Daw" },
  { tag: "MYN ", name: "Mayan" },
  { tag: "MZN ", name: "Mazanderani" },
  { tag: "NAG ", name: "Naga-Assamese" },
  { tag: "NAH ", name: "Nahuatl" },
  { tag: "NAN ", name: "Nanai" },
  { tag: "NAP ", name: "Neapolitan" },
  { tag: "NAS ", name: "Naskapi" },
  { tag: "NAU ", name: "Nauruan" },
  { tag: "NAV ", name: "Navajo" },
  { tag: "NCR ", name: "N-Cree" },
  { tag: "NDB ", name: "Ndebele" },
  { tag: "NDC ", name: "Ndau" },
  { tag: "NDG ", name: "Ndonga" },
  { tag: "NDS ", name: "Low Saxon" },
  { tag: "NEP ", name: "Nepali" },
  { tag: "NEW ", name: "Newari" },
  { tag: "NGA ", name: "Ngbaka" },
  { tag: "NGR ", name: "Nagari" },
  { tag: "NHC ", name: "Norway House Cree" },
  { tag: "NIS ", name: "Nisi" },
  { tag: "NIU ", name: "Niuean" },
  { tag: "NKL ", name: "Nyankole" },
  { tag: "NKO ", name: "N’Ko" },
  { tag: "NLD ", name: "Dutch" },
  { tag: "NOE ", name: "Nimadi" },
  { tag: "NOG ", name: "Nogai" },
  { tag: "NOR ", name: "Norwegian" },
  { tag: "NOV ", name: "Novial" },
  { tag: "NSM ", name: "Northern Sami" },
  { tag: "NSO ", name: "Sotho, Northern" },
  { tag: "NTA ", name: "Northern Tai" },
  { tag: "NTO ", name: "Esperanto" },
  { tag: "NYM ", name: "Nyamwezi" },
  { tag: "NYN ", name: "Norwegian Nynorsk (Nynorsk, Norwegian)" },
  { tag: "NZA ", name: "Mbembe Tigon" },
  { tag: "OCI ", name: "Occitan" },
  { tag: "OCR ", name: "Oji-Cree" },
  { tag: "OJB ", name: "Ojibway" },
  { tag: "ORI ", name: "Odia (formerly Oriya)" },
  { tag: "ORO ", name: "Oromo" },
  { tag: "OSS ", name: "Ossetian" },
  { tag: "PAA ", name: "Palestinian Aramaic" },
  { tag: "PAG ", name: "Pangasinan" },
  { tag: "PAL ", name: "Pali" },
  { tag: "PAM ", name: "Pampangan" },
  { tag: "PAN ", name: "Punjabi" },
  { tag: "PAP ", name: "Palpa" },
  { tag: "PAP0", name: "Papiamentu" },
  { tag: "PAS ", name: "Pashto" },
  { tag: "PAU ", name: "Palauan" },
  { tag: "PCC ", name: "Bouyei" },
  { tag: "PCD ", name: "Picard" },
  { tag: "PDC ", name: "Pennsylvania German" },
  { tag: "PGR ", name: "Polytonic Greek" },
  { tag: "PHK ", name: "Phake" },
  { tag: "PIH ", name: "Norfolk" },
  { tag: "PIL ", name: "Filipino" },
  { tag: "PLG ", name: "Palaung" },
  { tag: "PLK ", name: "Polish" },
  { tag: "PMS ", name: "Piemontese" },
  { tag: "PNB ", name: "Western Panjabi" },
  { tag: "POH ", name: "Pocomchi" },
  { tag: "PON ", name: "Pohnpeian" },
  { tag: "PRO ", name: "Provençal / Old Provençal" },
  { tag: "PTG ", name: "Portuguese" },
  { tag: "PWO ", name: "Western Pwo Karen" },
  { tag: "QIN ", name: "Chin" },
  { tag: "QUC ", name: "K’iche’" },
  { tag: "QUH ", name: "Quechua (Bolivia)" },
  { tag: "QUZ ", name: "Quechua" },
  { tag: "QVI ", name: "Quechua (Ecuador)" },
  { tag: "QWH ", name: "Quechua (Peru)" },
  { tag: "RAJ ", name: "Rajasthani" },
  { tag: "RAR ", name: "Rarotongan" },
  { tag: "RBU ", name: "Russian Buriat" },
  { tag: "RCR ", name: "R-Cree" },
  { tag: "REJ ", name: "Rejang" },
  { tag: "RIA ", name: "Riang" },
  { tag: "RIF ", name: "Tarifit" },
  { tag: "RIT ", name: "Ritarungo" },
  { tag: "RKW ", name: "Arakwal" },
  { tag: "RMS ", name: "Romansh" },
  { tag: "RMY ", name: "Vlax Romani" },
  { tag: "ROM ", name: "Romanian" },
  { tag: "ROY ", name: "Romany" },
  { tag: "RSY ", name: "Rusyn" },
  { tag: "RTM ", name: "Rotuman" },
  { tag: "RUA ", name: "Kinyarwanda" },
  { tag: "RUN ", name: "Rundi" },
  { tag: "RUP ", name: "Aromanian" },
  { tag: "RUS ", name: "Russian" },
  { tag: "SAD ", name: "Sadri" },
  { tag: "SAN ", name: "Sanskrit" },
  { tag: "SAS ", name: "Sasak" },
  { tag: "SAT ", name: "Santali" },
  { tag: "SAY ", name: "Sayisi" },
  { tag: "SCN ", name: "Sicilian" },
  { tag: "SCO ", name: "Scots" },
  { tag: "SEK ", name: "Sekota" },
  { tag: "SEL ", name: "Selkup" },
  { tag: "SGA ", name: "Old Irish" },
  { tag: "SGO ", name: "Sango" },
  { tag: "SGS ", name: "Samogitian" },
  { tag: "SHI ", name: "Tachelhit" },
  { tag: "SHN ", name: "Shan" },
  { tag: "SIB ", name: "Sibe" },
  { tag: "SID ", name: "Sidamo" },
  { tag: "SIG ", name: "Silte Gurage" },
  { tag: "SKS ", name: "Skolt Sami" },
  { tag: "SKY ", name: "Slovak" },
  { tag: "SCS ", name: "North Slavey" },
  { tag: "SLA ", name: "Slavey" },
  { tag: "SLV ", name: "Slovenian" },
  { tag: "SML ", name: "Somali" },
  { tag: "SMO ", name: "Samoan" },
  { tag: "SNA ", name: "Sena" },
  { tag: "SNA0", name: "Shona" },
  { tag: "SND ", name: "Sindhi" },
  { tag: "SNH ", name: "Sinhala (Sinhalese)" },
  { tag: "SNK ", name: "Soninke" },
  { tag: "SOG ", name: "Sodo Gurage" },
  { tag: "SOP ", name: "Songe" },
  { tag: "SOT ", name: "Sotho, Southern" },
  { tag: "SQI ", name: "Albanian" },
  { tag: "SRB ", name: "Serbian" },
  { tag: "SRD ", name: "Sardinian" },
  { tag: "SRK ", name: "Saraiki" },
  { tag: "SRR ", name: "Serer" },
  { tag: "SSL ", name: "South Slavey" },
  { tag: "SSM ", name: "Southern Sami" },
  { tag: "STQ ", name: "Saterland Frisian" },
  { tag: "SUK ", name: "Sukuma" },
  { tag: "SUN ", name: "Sundanese" },
  { tag: "SUR ", name: "Suri" },
  { tag: "SVA ", name: "Svan" },
  { tag: "SVE ", name: "Swedish" },
  { tag: "SWA ", name: "Swadaya Aramaic" },
  { tag: "SWK ", name: "Swahili" },
  { tag: "SWZ ", name: "Swati" },
  { tag: "SXT ", name: "Sutu" },
  { tag: "SXU ", name: "Upper Saxon" },
  { tag: "SYL ", name: "Sylheti" },
  { tag: "SYR ", name: "Syriac" },
  { tag: "SYRE", name: "Syriac, Estrangela script-variant (equivalent to ISO 15924 'Syre')" },
  { tag: "SYRJ", name: "Syriac, Western script-variant (equivalent to ISO 15924 'Syrj')" },
  { tag: "SYRN", name: "Syriac, Eastern script-variant (equivalent to ISO 15924 'Syrn')" },
  { tag: "SZL ", name: "Silesian" },
  { tag: "TAB ", name: "Tabasaran" },
  { tag: "TAJ ", name: "Tajiki" },
  { tag: "TAM ", name: "Tamil" },
  { tag: "TAT ", name: "Tatar" },
  { tag: "TCR ", name: "TH-Cree" },
  { tag: "TDD ", name: "Dehong Dai" },
  { tag: "TEL ", name: "Telugu" },
  { tag: "TET ", name: "Tetum" },
  { tag: "TGL ", name: "Tagalog" },
  { tag: "TGN ", name: "Tongan" },
  { tag: "TGR ", name: "Tigre" },
  { tag: "TGY ", name: "Tigrinya" },
  { tag: "THA ", name: "Thai" },
  { tag: "THT ", name: "Tahitian" },
  { tag: "TIB ", name: "Tibetan" },
  { tag: "TIV ", name: "Tiv" },
  { tag: "TKM ", name: "Turkmen" },
  { tag: "TMH ", name: "Tamashek" },
  { tag: "TMN ", name: "Temne" },
  { tag: "TNA ", name: "Tswana" },
  { tag: "TNE ", name: "Tundra Nenets" },
  { tag: "TNG ", name: "Tonga" },
  { tag: "TOD ", name: "Todo" },
  { tag: "TOD0", name: "Toma" },
  { tag: "TPI ", name: "Tok Pisin" },
  { tag: "TRK ", name: "Turkish" },
  { tag: "TSG ", name: "Tsonga" },
  { tag: "TSJ ", name: "Tshangla" },
  { tag: "TUA ", name: "Turoyo Aramaic" },
  { tag: "TUM ", name: "Tulu" },
  { tag: "TUL ", name: "Tumbuka" },
  { tag: "TUV ", name: "Tuvin" },
  { tag: "TVL ", name: "Tuvalu" },
  { tag: "TWI ", name: "Twi" },
  { tag: "TYZ ", name: "Tày" },
  { tag: "TZM ", name: "Tamazight" },
  { tag: "TZO ", name: "Tzotzil" },
  { tag: "UDM ", name: "Udmurt" },
  { tag: "UKR ", name: "Ukrainian" },
  { tag: "UMB ", name: "Umbundu" },
  { tag: "URD ", name: "Urdu" },
  { tag: "USB ", name: "Upper Sorbian" },
  { tag: "UYG ", name: "Uyghur" },
  { tag: "UZB ", name: "Uzbek" },
  { tag: "VEC ", name: "Venetian" },
  { tag: "VEN ", name: "Venda" },
  { tag: "VIT ", name: "Vietnamese" },
  { tag: "VOL ", name: "Volapük" },
  { tag: "VRO ", name: "Võro" },
  { tag: "WA", name: "Wa" },
  { tag: "WAG ", name: "Wagdi" },
  { tag: "WAR ", name: "Waray-Waray" },
  { tag: "WCR ", name: "West-Cree" },
  { tag: "WEL ", name: "Welsh" },
  { tag: "WLN ", name: "Walloon" },
  { tag: "WLF ", name: "Wolof" },
  { tag: "WTM ", name: "Mewati" },
  { tag: "XBD ", name: "Lü" },
  { tag: "XKF ", name: "Khengkha" },
  { tag: "XHS ", name: "Xhosa" },
  { tag: "XJB ", name: "Minjangbal" },
  { tag: "XOG ", name: "Soga" },
  { tag: "XPE ", name: "Kpelle (Liberia)" },
  { tag: "YAK ", name: "Sakha" },
  { tag: "YAO ", name: "Yao" },
  { tag: "YAP ", name: "Yapese" },
  { tag: "YBA ", name: "Yoruba" },
  { tag: "YCR ", name: "Y-Cree" },
  { tag: "YIC ", name: "Yi Classic" },
  { tag: "YIM ", name: "Yi Modern" },
  { tag: "ZEA ", name: "Zealandic" },
  { tag: "ZGH ", name: "Standard Moroccan Tamazight" },
  { tag: "ZHA ", name: "Zhuang" },
  { tag: "ZHH ", name: "Chinese, Hong Kong SAR" },
  { tag: "ZHP ", name: "Chinese Phonetic" },
  { tag: "ZHS ", name: "Chinese Simplified" },
  { tag: "ZHT ", name: "Chinese Traditional" },
  { tag: "ZND ", name: "Zande" },
  { tag: "ZUL ", name: "Zulu" },
  { tag: "ZZA ", name: "Zazaki" },
];