module.exports = [
  { name: "Abkhazian", opentypeTag: "ABK ", htmlTag: "ab" },
  { name: "Afrikaans", opentypeTag: "AFK ", htmlTag: "af" },
  { name: "Afar", opentypeTag: "AFR ", htmlTag: "aa" },
  { name: "Akan", opentypeTag: "AKA ", htmlTag: "ak" },
  { name: "Amharic", opentypeTag: "AMH ", htmlTag: "am" },
  { name: "Arabic", opentypeTag: "ARA ", htmlTag: "ar" },
  { name: "Aragonese", opentypeTag: "ARG ", htmlTag: "an" },
  { name: "Rakhine", opentypeTag: "ARK ", htmlTag: "mhv" },
  { name: "Assamese", opentypeTag: "ASM ", htmlTag: "as" },
  { name: "Avar", opentypeTag: "AVR ", htmlTag: "av" },
  { name: "Aymara", opentypeTag: "AYM ", htmlTag: "ay" },
  { name: "Azerbaijani", opentypeTag: "AZE ", htmlTag: "az" },
  { name: "Banda", opentypeTag: "BAD0", htmlTag: "bad" },
  { name: "Belarussian", opentypeTag: "BEL ", htmlTag: "be" },
  { name: "Bengali", opentypeTag: "BEN ", htmlTag: "bn" },
  { name: "Bulgarian", opentypeTag: "BGR ", htmlTag: "bg" },
  { name: "Bislama", opentypeTag: "BIS ", htmlTag: "bi" },
  { name: "Bambara (Bamanankan)", opentypeTag: "BMB ", htmlTag: "bm" },
  { name: "Bosnian", opentypeTag: "BOS ", htmlTag: "bs" },
  { name: "Breton", opentypeTag: "BRE ", htmlTag: "br" },
  { name: "Burmese", opentypeTag: "BRM ", htmlTag: "my" },
  { name: "Bashkir", opentypeTag: "BSH ", htmlTag: "ba" },
  { name: "Beti", opentypeTag: "BTI ", htmlTag: "btb" },
  { name: "Catalan", opentypeTag: "CAT ", htmlTag: "ca" },
  { name: "Chechen", opentypeTag: "CHE ", htmlTag: "ce" },
  { name: "Chichewa (Chewa, Nyanja)", opentypeTag: "CHI ", htmlTag: "ny" },
  { name: "Chamorro", opentypeTag: "CHA ", htmlTag: "ch" },
  { name: "Chuvash", opentypeTag: "CHU ", htmlTag: "cv" },
  { name: "Cornish", opentypeTag: "COR ", htmlTag: "kw" },
  { name: "Corsican", opentypeTag: "COS ", htmlTag: "co" },
  { name: "Creoles", opentypeTag: "CPP ", htmlTag: "crp" },
  { name: "Cree", opentypeTag: "CRE ", htmlTag: "cr" },
  { name: "Church Slavonic", opentypeTag: "CSL ", htmlTag: "cu" },
  { name: "Czech", opentypeTag: "CSY ", htmlTag: "cs" },
  { name: "Danish", opentypeTag: "DAN ", htmlTag: "da" },
  { name: "German", opentypeTag: "DEU ", htmlTag: "de" },
  { name: "Divehi (Dhivehi, Maldivian)", opentypeTag: "DHV  (deprecated)", htmlTag: "dv" },
  { name: "Divehi (Dhivehi, Maldivian)", opentypeTag: "DIV ", htmlTag: "dv" },
  { name: "Dhuwal", opentypeTag: "DUJ ", htmlTag: "duj" },
  { name: "Dzongkha", opentypeTag: "DZN ", htmlTag: "dz" },
  { name: "Greek", opentypeTag: "ELL ", htmlTag: "el" },
  { name: "English", opentypeTag: "ENG ", htmlTag: "en" },
  { name: "Spanish", opentypeTag: "ESP ", htmlTag: "es" },
  { name: "Estonian", opentypeTag: "ETI ", htmlTag: "et" },
  { name: "Basque", opentypeTag: "EUQ ", htmlTag: "eu" },
  { name: "Ewe", opentypeTag: "EWE ", htmlTag: "ee" },
  { name: "Persian", opentypeTag: "FAR ", htmlTag: "fa" },
  { name: "Finnish", opentypeTag: "FIN ", htmlTag: "fi" },
  { name: "Fijian", opentypeTag: "FJI ", htmlTag: "fj" },
  { name: "Faroese", opentypeTag: "FOS ", htmlTag: "fo" },
  { name: "French", opentypeTag: "FRA ", htmlTag: "fr" },
  { name: "Frisian", opentypeTag: "FRI ", htmlTag: "fy" },
  { name: "Fulah", opentypeTag: "FUL ", htmlTag: "ff" },
  { name: "Scottish Gaelic (Gaelic)", opentypeTag: "GAE ", htmlTag: "gd" },
  { name: "Galician", opentypeTag: "GAL ", htmlTag: "gl" },
  { name: "Greenlandic", opentypeTag: "GRN ", htmlTag: "kl" },
  { name: "Guarani", opentypeTag: "GUA ", htmlTag: "gn" },
  { name: "Gujarati", opentypeTag: "GUJ ", htmlTag: "gu" },
  { name: "Haitian (Haitian Creole)", opentypeTag: "HAI ", htmlTag: "ht" },
  { name: "Halam (Falam Chin)", opentypeTag: "HAL ", htmlTag: "flm" },
  { name: "Hausa", opentypeTag: "HAU ", htmlTag: "ha" },
  { name: "Herero", opentypeTag: "HER ", htmlTag: "hz" },
  { name: "Hindi", opentypeTag: "HIN ", htmlTag: "hi" },
  { name: "Hiri Motu", opentypeTag: "HMO ", htmlTag: "ho" },
  { name: "Croatian", opentypeTag: "HRV ", htmlTag: "hr" },
  { name: "Hungarian", opentypeTag: "HUN ", htmlTag: "hu" },
  { name: "Armenian", opentypeTag: "HYE ", htmlTag: "hy" },
  { name: "Armenian East", opentypeTag: "HYE0", htmlTag: "hy" },
  { name: "Igbo", opentypeTag: "IBO ", htmlTag: "ig" },
  { name: "Ido", opentypeTag: "IDO ", htmlTag: "io" },
  { name: "Interlingue", opentypeTag: "ILE ", htmlTag: "ie" },
  { name: "Interlingua", opentypeTag: "INA ", htmlTag: "ia" },
  { name: "Indonesian", opentypeTag: "IND ", htmlTag: "id" },
  { name: "Inuktitut", opentypeTag: "INU ", htmlTag: "iu" },
  { name: "Inupiat", opentypeTag: "IPK ", htmlTag: "ik" },
  { name: "Irish", opentypeTag: "IRI ", htmlTag: "ga" },
  { name: "Irish Traditional", opentypeTag: "IRT ", htmlTag: "ga" },
  { name: "Icelandic", opentypeTag: "ISL ", htmlTag: "is" },
  { name: "Italian", opentypeTag: "ITA ", htmlTag: "it" },
  { name: "Hebrew", opentypeTag: "IWR ", htmlTag: "he" },
  { name: "Japanese", opentypeTag: "JAN ", htmlTag: "ja" },
  { name: "Javanese", opentypeTag: "JAV ", htmlTag: "jv" },
  { name: "Yiddish", opentypeTag: "JII ", htmlTag: "yi" },
  { name: "Kannada", opentypeTag: "KAN ", htmlTag: "kn" },
  { name: "Georgian", opentypeTag: "KAT ", htmlTag: "ka" },
  { name: "Kazakh", opentypeTag: "KAZ ", htmlTag: "kk" },
  { name: "Khutsuri Georgian", opentypeTag: "KGE ", htmlTag: "ka" },
  { name: "Khmer", opentypeTag: "KHM ", htmlTag: "km" },
  { name: "Kikuyu (Gikuyu)", opentypeTag: "KIK ", htmlTag: "ki" },
  { name: "Kirghiz (Kyrgyz)", opentypeTag: "KIR ", htmlTag: "ky" },
  { name: "Kanuri", opentypeTag: "KNR ", htmlTag: "kr" },
  { name: "Komi", opentypeTag: "KOM ", htmlTag: "kv" },
  { name: "Kongo", opentypeTag: "KON0", htmlTag: "kg" },
  { name: "Korean", opentypeTag: "KOR ", htmlTag: "ko" },
  { name: "Karen", opentypeTag: "KRN ", htmlTag: "kar" },
  { name: "Kashmiri", opentypeTag: "KSH ", htmlTag: "ks" },
  { name: "Kuanyama", opentypeTag: "KUA ", htmlTag: "kj" },
  { name: "Kurdish", opentypeTag: "KUR ", htmlTag: "ku" },
  { name: "Lao", opentypeTag: "LAO ", htmlTag: "lo" },
  { name: "Latin", opentypeTag: "LAT ", htmlTag: "la" },
  { name: "Limburgish", opentypeTag: "LIM ", htmlTag: "li" },
  { name: "Lingala", opentypeTag: "LIN ", htmlTag: "ln" },
  { name: "Lithuanian", opentypeTag: "LTH ", htmlTag: "lt" },
  { name: "Luxembourgish", opentypeTag: "LTZ ", htmlTag: "lb" },
  { name: "Luba-Katanga", opentypeTag: "LUB ", htmlTag: "lu" },
  { name: "Ganda", opentypeTag: "LUG ", htmlTag: "lg" },
  { name: "Latvian", opentypeTag: "LVI ", htmlTag: "lv" },
  { name: "Marshallese", opentypeTag: "MAH ", htmlTag: "mh" },
  { name: "Malayalam", opentypeTag: "MAL ", htmlTag: "ml" },
  { name: "Marathi", opentypeTag: "MAR ", htmlTag: "mr" },
  { name: "Macedonian", opentypeTag: "MKD ", htmlTag: "mk" },
  { name: "Malagasy", opentypeTag: "MLG ", htmlTag: "mg" },
  { name: "Malayalam Reformed", opentypeTag: "MLR ", htmlTag: "ml" },
  { name: "Malay", opentypeTag: "MLY ", htmlTag: "ms" },
  { name: "Mongolian", opentypeTag: "MNG ", htmlTag: "mn" },
  { name: "Manx", opentypeTag: "MNX ", htmlTag: "gv" },
  { name: "Moldavian", opentypeTag: "MOL ", htmlTag: "mol" },
  { name: "Maori", opentypeTag: "MRI ", htmlTag: "mi" },
  { name: "Maltese", opentypeTag: "MTS ", htmlTag: "mt" },
  { name: "Mayan", opentypeTag: "MYN ", htmlTag: "myn" },
  { name: "Nahuatl", opentypeTag: "NAH ", htmlTag: "nah" },
  { name: "Nauruan", opentypeTag: "NAU ", htmlTag: "na" },
  { name: "Navajo", opentypeTag: "NAV ", htmlTag: "nv" },
  { name: "Ndebele", opentypeTag: "NDB ", htmlTag: "nr" },
  { name: "Ndonga", opentypeTag: "NDG ", htmlTag: "ng" },
  { name: "Nepali", opentypeTag: "NEP ", htmlTag: "ne" },
  { name: "Nisi", opentypeTag: "NIS ", htmlTag: "dap" },
  { name: "Dutch", opentypeTag: "NLD ", htmlTag: "nl" },
  { name: "Norwegian", opentypeTag: "NOR ", htmlTag: "nb" },
  { name: "Northern Sami", opentypeTag: "NSM ", htmlTag: "se" },
  { name: "Esperanto", opentypeTag: "NTO ", htmlTag: "eo" },
  { name: "Norwegian Nynorsk (Nynorsk, Norwegian)", opentypeTag: "NYN ", htmlTag: "nn" },
  { name: "Occitan", opentypeTag: "OCI ", htmlTag: "oc" },
  { name: "Ojibway", opentypeTag: "OJB ", htmlTag: "oj" },
  { name: "Odia (formerly Oriya)", opentypeTag: "ORI ", htmlTag: "or" },
  { name: "Oromo", opentypeTag: "ORO ", htmlTag: "om" },
  { name: "Ossetian", opentypeTag: "OSS ", htmlTag: "os" },
  { name: "Pali", opentypeTag: "PAL ", htmlTag: "pi" },
  { name: "Punjabi", opentypeTag: "PAN ", htmlTag: "pa" },
  { name: "Pashto", opentypeTag: "PAS ", htmlTag: "ps" },
  { name: "Polytonic Greek", opentypeTag: "PGR ", htmlTag: "el" },
  { name: "Polish", opentypeTag: "PLK ", htmlTag: "pl" },
  { name: "Portuguese", opentypeTag: "PTG ", htmlTag: "pt" },
  { name: "Romansh", opentypeTag: "RMS ", htmlTag: "rm" },
  { name: "Romanian", opentypeTag: "ROM ", htmlTag: "ro" },
  { name: "Kinyarwanda", opentypeTag: "RUA ", htmlTag: "rw" },
  { name: "Rundi", opentypeTag: "RUN ", htmlTag: "rn" },
  { name: "Russian", opentypeTag: "RUS ", htmlTag: "ru" },
  { name: "Sanskrit", opentypeTag: "SAN ", htmlTag: "sa" },
  { name: "Sango", opentypeTag: "SGO ", htmlTag: "sg" },
  { name: "Silte Gurage", opentypeTag: "SIG ", htmlTag: "xst" },
  { name: "Slovak", opentypeTag: "SKY ", htmlTag: "sk" },
  { name: "Slovenian", opentypeTag: "SLV ", htmlTag: "sl" },
  { name: "Somali", opentypeTag: "SML ", htmlTag: "so" },
  { name: "Samoan", opentypeTag: "SMO ", htmlTag: "sm" },
  { name: "Shona", opentypeTag: "SNA0", htmlTag: "sn" },
  { name: "Sindhi", opentypeTag: "SND ", htmlTag: "sd" },
  { name: "Sinhala (Sinhalese)", opentypeTag: "SNH ", htmlTag: "si" },
  { name: "Sotho, Southern", opentypeTag: "SOT ", htmlTag: "st" },
  { name: "Albanian", opentypeTag: "SQI ", htmlTag: "sq" },
  { name: "Serbian", opentypeTag: "SRB ", htmlTag: "sr" },
  { name: "Sardinian", opentypeTag: "SRD ", htmlTag: "sc" },
  { name: "Sundanese", opentypeTag: "SUN ", htmlTag: "su" },
  { name: "Swedish", opentypeTag: "SVE ", htmlTag: "sv" },
  { name: "Swahili", opentypeTag: "SWK ", htmlTag: "sw" },
  { name: "Swati", opentypeTag: "SWZ ", htmlTag: "ss" },
  { name: "Tajiki", opentypeTag: "TAJ ", htmlTag: "tg" },
  { name: "Tamil", opentypeTag: "TAM ", htmlTag: "ta" },
  { name: "Tatar", opentypeTag: "TAT ", htmlTag: "tt" },
  { name: "Telugu", opentypeTag: "TEL ", htmlTag: "te" },
  { name: "Tagalog", opentypeTag: "TGL ", htmlTag: "tl" },
  { name: "Tongan", opentypeTag: "TGN ", htmlTag: "to" },
  { name: "Tigrinya", opentypeTag: "TGY ", htmlTag: "ti" },
  { name: "Thai", opentypeTag: "THA ", htmlTag: "th" },
  { name: "Tahitian", opentypeTag: "THT ", htmlTag: "ty" },
  { name: "Tibetan", opentypeTag: "TIB ", htmlTag: "bo" },
  { name: "Turkmen", opentypeTag: "TKM ", htmlTag: "tk" },
  { name: "Tswana", opentypeTag: "TNA ", htmlTag: "tn" },
  { name: "Turkish", opentypeTag: "TRK ", htmlTag: "tr" },
  { name: "Tsonga", opentypeTag: "TSG ", htmlTag: "ts" },
  { name: "Twi", opentypeTag: "TWI ", htmlTag: "ak" },
  { name: "Ukrainian", opentypeTag: "UKR ", htmlTag: "uk" },
  { name: "Urdu", opentypeTag: "URD ", htmlTag: "ur" },
  { name: "Uyghur", opentypeTag: "UYG ", htmlTag: "ug" },
  { name: "Uzbek", opentypeTag: "UZB ", htmlTag: "uz" },
  { name: "Venda", opentypeTag: "VEN ", htmlTag: "ve" },
  { name: "Vietnamese", opentypeTag: "VIT ", htmlTag: "vi" },
  { name: "Volapük", opentypeTag: "VOL ", htmlTag: "vo" },
  { name: "Welsh", opentypeTag: "WEL ", htmlTag: "cy" },
  { name: "Walloon", opentypeTag: "WLN ", htmlTag: "wa" },
  { name: "Wolof", opentypeTag: "WLF ", htmlTag: "wo" },
  { name: "Xhosa", opentypeTag: "XHS ", htmlTag: "xh" },
  { name: "Yoruba", opentypeTag: "YBA ", htmlTag: "yo" },
  { name: "Y-Cree", opentypeTag: "YCR ", htmlTag: "cr" },
  { name: "Yi Modern", opentypeTag: "YIM ", htmlTag: "ii" },
  { name: "Zhuang", opentypeTag: "ZHA ", htmlTag: "za" },
  { name: "Chinese, Hong Kong SAR", opentypeTag: "ZHH ", htmlTag: "zh" },
  { name: "Chinese Phonetic", opentypeTag: "ZHP ", htmlTag: "zh" },
  { name: "Chinese Simplified", opentypeTag: "ZHS ", htmlTag: "zh" },
  { name: "Chinese Traditional", opentypeTag: "ZHT ", htmlTag: "zh" },
  { name: "Zulu", opentypeTag: "ZUL ", htmlTag: "zu" },
];