export function getOpenTypeFeatureName(tag) {
  const match = opentypeFeatureNames.find(f => f.tag.test(tag));
  return match ? tag.replace(match.tag, match.name) : tag;
}

const opentypeFeatureNames = [
  { tag: /aalt/, name: "Access All Alternates" },
  { tag: /abvf/, name: "Above-base Forms" },
  { tag: /abvm/, name: "Above-base Mark Positioning" },
  { tag: /abvs/, name: "Above-base Substitutions" },
  { tag: /afrc/, name: "Alternative Fractions" },
  { tag: /akhn/, name: "Akhands" },
  { tag: /blwf/, name: "Below-base Forms" },
  { tag: /blwm/, name: "Below-base Mark Positioning" },
  { tag: /blws/, name: "Below-base Substitutions" },
  { tag: /calt/, name: "Contextual Alternates" },
  { tag: /case/, name: "Case-Sensitive Forms" },
  { tag: /ccmp/, name: "Glyph Composition / Decomposition" },
  { tag: /cfar/, name: "Conjunct Form After Ro" },
  { tag: /cjct/, name: "Conjunct Forms" },
  { tag: /clig/, name: "Contextual Ligatures" },
  { tag: /cpct/, name: "Centered CJK Punctuation" },
  { tag: /cpsp/, name: "Capital Spacing" },
  { tag: /cswh/, name: "Contextual Swash" },
  { tag: /curs/, name: "Cursive Positioning" },
  { tag: /cv(\d{2})/, name: "Character Variants $1" },
  { tag: /c2pc/, name: "Petite Capitals From Capitals" },
  { tag: /c2sc/, name: "Small Capitals From Capitals" },
  { tag: /dist/, name: "Distances" },
  { tag: /dlig/, name: "Discretionary Ligatures" },
  { tag: /dnom/, name: "Denominators" },
  { tag: /dtls/, name: "Dotless Forms" },
  { tag: /expt/, name: "Expert Forms" },
  { tag: /falt/, name: "Final Glyph on Line Alternates" },
  { tag: /fin2/, name: "Terminal Forms #2" },
  { tag: /fin3/, name: "Terminal Forms #3" },
  { tag: /fina/, name: "Terminal Forms" },
  { tag: /flac/, name: "Flattened accent forms" },
  { tag: /frac/, name: "Fractions" },
  { tag: /fwid/, name: "Full Widths" },
  { tag: /half/, name: "Half Forms" },
  { tag: /haln/, name: "Halant Forms" },
  { tag: /halt/, name: "Alternate Half Widths" },
  { tag: /hist/, name: "Historical Forms" },
  { tag: /hkna/, name: "Horizontal Kana Alternates" },
  { tag: /hlig/, name: "Historical Ligatures" },
  { tag: /hngl/, name: "Hangul" },
  { tag: /hojo/, name: "Hojo Kanji Forms (JIS X 0212-1990 Kanji Forms)" },
  { tag: /hwid/, name: "Half Widths" },
  { tag: /init/, name: "Initial Forms" },
  { tag: /isol/, name: "Isolated Forms" },
  { tag: /ital/, name: "Italics" },
  { tag: /jalt/, name: "Justification Alternates" },
  { tag: /jp78/, name: "JIS78 Forms" },
  { tag: /jp83/, name: "JIS83 Forms" },
  { tag: /jp90/, name: "JIS90 Forms" },
  { tag: /jp04/, name: "JIS2004 Forms" },
  { tag: /kern/, name: "Kerning" },
  { tag: /lfbd/, name: "Left Bounds" },
  { tag: /liga/, name: "Standard Ligatures" },
  { tag: /ljmo/, name: "Leading Jamo Forms" },
  { tag: /lnum/, name: "Lining Figures" },
  { tag: /locl/, name: "Localized Forms" },
  { tag: /ltra/, name: "Left-to-right alternates" },
  { tag: /ltrm/, name: "Left-to-right mirrored forms" },
  { tag: /mark/, name: "Mark Positioning" },
  { tag: /med2/, name: "Medial Forms #2" },
  { tag: /medi/, name: "Medial Forms" },
  { tag: /mgrk/, name: "Mathematical Greek" },
  { tag: /mkmk/, name: "Mark to Mark Positioning" },
  { tag: /mset/, name: "Mark Positioning via Substitution" },
  { tag: /nalt/, name: "Alternate Annotation Forms" },
  { tag: /nlck/, name: "NLC Kanji Forms" },
  { tag: /nukt/, name: "Nukta Forms" },
  { tag: /numr/, name: "Numerators" },
  { tag: /onum/, name: "Oldstyle Figures" },
  { tag: /opbd/, name: "Optical Bounds" },
  { tag: /ordn/, name: "Ordinals" },
  { tag: /ornm/, name: "Ornaments" },
  { tag: /palt/, name: "Proportional Alternate Widths" },
  { tag: /pcap/, name: "Petite Capitals" },
  { tag: /pkna/, name: "Proportional Kana" },
  { tag: /pnum/, name: "Proportional Figures" },
  { tag: /pref/, name: "Pre-Base Forms" },
  { tag: /pres/, name: "Pre-base Substitutions" },
  { tag: /pstf/, name: "Post-base Forms" },
  { tag: /psts/, name: "Post-base Substitutions" },
  { tag: /pwid/, name: "Proportional Widths" },
  { tag: /qwid/, name: "Quarter Widths" },
  { tag: /rand/, name: "Randomize" },
  { tag: /rclt/, name: "Required Contextual Alternates" },
  { tag: /rkrf/, name: "Rakar Forms" },
  { tag: /rlig/, name: "Required Ligatures" },
  { tag: /rphf/, name: "Reph Forms" },
  { tag: /rtbd/, name: "Right Bounds" },
  { tag: /rtla/, name: "Right-to-left alternates" },
  { tag: /rtlm/, name: "Right-to-left mirrored forms" },
  { tag: /ruby/, name: "Ruby Notation Forms" },
  { tag: /rvrn/, name: "Required Variation Alternates" },
  { tag: /salt/, name: "Stylistic Alternates" },
  { tag: /sinf/, name: "Scientific Inferiors" },
  { tag: /size/, name: "Optical size" },
  { tag: /smcp/, name: "Small Capitals" },
  { tag: /smpl/, name: "Simplified Forms" },
  { tag: /ss01/, name: "Stylistic Set 1" },
  { tag: /ss02/, name: "Stylistic Set 2" },
  { tag: /ss03/, name: "Stylistic Set 3" },
  { tag: /ss04/, name: "Stylistic Set 4" },
  { tag: /ss05/, name: "Stylistic Set 5" },
  { tag: /ss06/, name: "Stylistic Set 6" },
  { tag: /ss07/, name: "Stylistic Set 7" },
  { tag: /ss08/, name: "Stylistic Set 8" },
  { tag: /ss09/, name: "Stylistic Set 9" },
  { tag: /ss10/, name: "Stylistic Set 10" },
  { tag: /ss11/, name: "Stylistic Set 11" },
  { tag: /ss12/, name: "Stylistic Set 12" },
  { tag: /ss13/, name: "Stylistic Set 13" },
  { tag: /ss14/, name: "Stylistic Set 14" },
  { tag: /ss15/, name: "Stylistic Set 15" },
  { tag: /ss16/, name: "Stylistic Set 16" },
  { tag: /ss17/, name: "Stylistic Set 17" },
  { tag: /ss18/, name: "Stylistic Set 18" },
  { tag: /ss19/, name: "Stylistic Set 19" },
  { tag: /ss20/, name: "Stylistic Set 20" },
  { tag: /ssty/, name: "Math script style alternates" },
  { tag: /stch/, name: "Stretching Glyph Decomposition" },
  { tag: /subs/, name: "Subscript" },
  { tag: /sups/, name: "Superscript" },
  { tag: /swsh/, name: "Swash" },
  { tag: /titl/, name: "Titling" },
  { tag: /tjmo/, name: "Trailing Jamo Forms" },
  { tag: /tnam/, name: "Traditional Name Forms" },
  { tag: /tnum/, name: "Tabular Figures" },
  { tag: /trad/, name: "Traditional Forms" },
  { tag: /twid/, name: "Third Widths" },
  { tag: /unic/, name: "Unicase" },
  { tag: /valt/, name: "Alternate Vertical Metrics" },
  { tag: /vatu/, name: "Vattu Variants" },
  { tag: /vert/, name: "Vertical Writing" },
  { tag: /vhal/, name: "Alternate Vertical Half Metrics" },
  { tag: /vjmo/, name: "Vowel Jamo Forms" },
  { tag: /vkna/, name: "Vertical Kana Alternates" },
  { tag: /vkrn/, name: "Vertical Kerning" },
  { tag: /vpal/, name: "Proportional Alternate Vertical Metrics" },
  { tag: /vrt2/, name: "Vertical Alternates and Rotation" },
  { tag: /vrtr/, name: "Vertical Alternates for Rotation" },
  { tag: /zero/, name: "Slashed Zero" },
];
